// Thai Reading Quest - Curriculum Data

/** Look-alike consonants that need an explicit contrast slide + forced test items. */
const CONFUSING_PAIRS = [
  {
    id: 'mo-tho',
    a: 'ม', b: 'ท',
    aSound: 'm', bSound: 'th',
    aName: 'mo ma', bName: 'tho thahan',
    tip: 'ม (m) looks more open and rounded. ท (th) has a sharper notch where the curve meets the left stem — like a small “bite.”',
    compare: [
      {thai: 'มา', roman: 'maa', note: 'ม + า'},
      {thai: 'ทา', roman: 'thaa', note: 'ท + า'},
      {thai: 'โม', roman: 'mo', note: 'โ + ม'},
      {thai: 'โท', roman: 'tho', note: 'โ + ท'},
    ],
    wordsA: ['maa', 'mo'],
    wordsB: ['thaa', 'tho'],
    introducedIn: 'medium-3',
  },
];

const SYMBOLS = [
  {symbol:'ก',type:'consonant',sound:'k/g',introducedIn:'basic-1',warning:'Learners may hear this between English k and g.',exampleWordId:'gaa',role:'consonant'},
  {symbol:'ม',type:'consonant',sound:'m',introducedIn:'basic-1',exampleWordId:'maa',role:'consonant'},
  {symbol:'า',type:'vowel',sound:'aa',introducedIn:'basic-1',role:'long vowel written after the consonant',exampleWordId:'maa'},
  {symbol:'น',type:'consonant',sound:'n',introducedIn:'basic-2',exampleWordId:'naa',role:'consonant'},
  {symbol:'ะ',type:'vowel',sound:'a',introducedIn:'basic-3',role:'short vowel',exampleWordId:'ka'},
  {symbol:'ิ',type:'vowel',sound:'i',introducedIn:'basic-4',role:'short vowel above consonant',exampleWordId:'mi'},
  {symbol:'ี',type:'vowel',sound:'ii',introducedIn:'basic-4',role:'long vowel above consonant',exampleWordId:'mii'},
  {symbol:'เ-',type:'vowel',sound:'e',introducedIn:'basic-5',role:'vowel written before consonant',exampleWordId:'ke',warning:'Written before the consonant but pronounced after it. With ะ it forms one short e (เ-ะ), not “e” + “a”.'},
  {symbol:'ป',type:'consonant',sound:'bp/p',introducedIn:'basic-6',exampleWordId:'paa',role:'consonant',warning:'Unaspirated p — different from บ.'},
  {symbol:'บ',type:'consonant',sound:'b',introducedIn:'basic-6',exampleWordId:'baa',role:'consonant',warning:'Similar to ป — watch the loop at bottom.'},
  {symbol:'โ-',type:'vowel',sound:'o',introducedIn:'basic-7',role:'vowel written before consonant',exampleWordId:'ko',warning:'With ะ it forms one short o (โ-ะ), not “o” + “a”.'},
  {symbol:'ต',type:'consonant',sound:'dt/t',introducedIn:'basic-8',exampleWordId:'taa',role:'consonant'},
  {symbol:'ล',type:'consonant',sound:'l',introducedIn:'basic-9',exampleWordId:'laa',role:'consonant'},
  {symbol:'ร',type:'consonant',sound:'r',introducedIn:'basic-9',exampleWordId:'raa',role:'consonant',warning:'Can sound like l in casual speech.'},
  {symbol:'ง',type:'consonant',sound:'ng',introducedIn:'basic-10',exampleWordId:'ngaa',role:'consonant'},
  {symbol:'ค',type:'consonant',sound:'kh',introducedIn:'medium-1',exampleWordId:'khaa',role:'consonant',warning:'Aspirated — not the same as ก.'},
  {symbol:'พ',type:'consonant',sound:'ph',introducedIn:'medium-1',exampleWordId:'phaa',role:'consonant'},
  {symbol:'ห',type:'consonant',sound:'h',introducedIn:'medium-1',exampleWordId:'haa',role:'consonant'},
  {symbol:'ว',type:'consonant',sound:'w',introducedIn:'medium-2',exampleWordId:'waa',role:'consonant'},
  {symbol:'ย',type:'consonant',sound:'y',introducedIn:'medium-2',exampleWordId:'yaa',role:'consonant'},
  {symbol:'จ',type:'consonant',sound:'j',introducedIn:'medium-2',exampleWordId:'jaa',role:'consonant'},
  {symbol:'ด',type:'consonant',sound:'d',introducedIn:'medium-3',exampleWordId:'duu',role:'consonant'},
  {symbol:'ท',type:'consonant',sound:'th',introducedIn:'medium-3',exampleWordId:'thaa',role:'consonant',warning:'Easy to confuse with ม (m) in modern fonts — watch the notch on ท.'},
  {symbol:'ช',type:'consonant',sound:'ch',introducedIn:'medium-3',exampleWordId:'chaa',role:'consonant'},
  {symbol:'ู',type:'vowel',sound:'uu',introducedIn:'medium-3',role:'long vowel below consonant',exampleWordId:'duu'},
  {symbol:'อ',type:'consonant',sound:'(silent carrier)',introducedIn:'medium-4',exampleWordId:'aa_carrier',role:'vowel carrier / glottal onset'},
  {symbol:'แ-',type:'vowel',sound:'ae',introducedIn:'medium-5',role:'vowel written before consonant',exampleWordId:'gae'},
  {symbol:'ุ',type:'vowel',sound:'u',introducedIn:'medium-6',role:'short vowel below consonant',exampleWordId:'pu'},
  {symbol:'ไ-',type:'vowel',sound:'ai',introducedIn:'medium-7',role:'vowel written before consonant',exampleWordId:'bpai'},
  {symbol:'ใ-',type:'vowel',sound:'ai',introducedIn:'medium-7',role:'vowel — limited usage',exampleWordId:'bai',warning:'Used in only ~20 common words.'},
  {symbol:'เ-า',type:'vowel',sound:'ao',introducedIn:'medium-8',role:'combined vowel pattern',exampleWordId:'mao'},
  {symbol:'ข',type:'consonant',sound:'kh',introducedIn:'advanced-1',exampleWordId:'khaa2',role:'consonant'},
  {symbol:'ส',type:'consonant',sound:'s',introducedIn:'advanced-1',exampleWordId:'sii',role:'consonant'},
  {symbol:'ฟ',type:'consonant',sound:'f',introducedIn:'advanced-1',exampleWordId:'faa',role:'consonant'},
  {symbol:'ซ',type:'consonant',sound:'s',introducedIn:'advanced-1',exampleWordId:'saa',role:'consonant'},
  {symbol:'ถ',type:'consonant',sound:'th',introducedIn:'advanced-1',exampleWordId:'thaa2',role:'consonant'},
  {symbol:'ผ',type:'consonant',sound:'ph',introducedIn:'advanced-1',exampleWordId:'phaa2',role:'consonant'},
  {symbol:'ฝ',type:'consonant',sound:'f',introducedIn:'advanced-1',exampleWordId:'faa2',role:'consonant'},
  {symbol:'่',type:'tone mark',sound:'(low tone mark)',introducedIn:'advanced-2',role:'mai ek tone mark'},
  {symbol:'้',type:'tone mark',sound:'(falling tone mark)',introducedIn:'advanced-2',role:'mai tho tone mark'},
  {symbol:'๊',type:'tone mark',sound:'(high tone mark)',introducedIn:'advanced-3',role:'mai tri tone mark'},
  {symbol:'๋',type:'tone mark',sound:'(rising tone mark)',introducedIn:'advanced-3',role:'mai chattawa tone mark'},
  {symbol:'์',type:'special mark',sound:'(silent)',introducedIn:'advanced-6',role:'silent mark / garan'},
  {symbol:'ำ',type:'vowel',sound:'am',introducedIn:'advanced-2',role:'special vowel form',exampleWordId:'naam'},
];

/**
 * WORD BANK RULES
 * - Never test letter≠sound exceptions before those rules are taught
 *   (especially final ด/ต → t and บ/ป → p before medium-9’s final-sound deep dive).
 * - Prefer sonorant finals น / ม / ง early; use final ก only as k once closed syllables are taught.
 * - Every word must be a real dictionary form with a real meaning (no “(syllable)” fillers).
 * - `emoji` (1–2) is shown on the answer feedback card with the meaning.
 */
const WORDS = [
  {id:'gaa',thai:'กา',romanizations:['kaa','gaa'],meaning:'crow',emoji:'🐦',level:'basic',lessonId:'basic-1',consonants:['ก'],vowels:['า'],rules:['open-syllable'],explanation:'ก = k/g, า = long aa.'},
  {id:'maa',thai:'มา',romanizations:['maa'],meaning:'come',emoji:'👋',level:'basic',lessonId:'basic-1',consonants:['ม'],vowels:['า'],rules:['open-syllable'],explanation:'ม = m, า = long aa.'},
  {id:'naa',thai:'นา',romanizations:['naa'],meaning:'field / rice field',emoji:'🌾',level:'basic',lessonId:'basic-2',consonants:['น'],vowels:['า'],rules:['open-syllable'],explanation:'น = n, า = aa.'},
  {id:'ma',thai:'มานะ',romanizations:['maa-na','maana'],meaning:'perseverance / determination',emoji:'💪',level:'basic',lessonId:'basic-3',consonants:['ม','น'],vowels:['า','ะ'],rules:['open-syllable'],explanation:'มานะ = maa + na. Short a with ะ.'},
  {id:'ka',thai:'กะ',romanizations:['ka','ga'],meaning:'to estimate / a portion',emoji:'⚖️',level:'basic',lessonId:'basic-3',consonants:['ก'],vowels:['ะ'],rules:['open-syllable'],explanation:'Short a vowel.'},
  {id:'na',thai:'นานา',romanizations:['naa-naa','naanaa'],meaning:'various / diverse',emoji:'🌈',level:'basic',lessonId:'basic-3',consonants:['น'],vowels:['า'],rules:['open-syllable'],explanation:'นา + นา — practice น and long aa.'},
  {id:'mi',thai:'มิ',romanizations:['mi'],meaning:'not (formal)',emoji:'🚫',level:'basic',lessonId:'basic-4',consonants:['ม'],vowels:['ิ'],rules:['open-syllable'],explanation:'Short i. Formal/literary “not”.'},
  {id:'mii',thai:'มี',romanizations:['mii'],meaning:'have / there is',emoji:'✅',level:'basic',lessonId:'basic-4',consonants:['ม'],vowels:['ี'],rules:['open-syllable'],explanation:'Long ii above consonant.'},
  {id:'ni',thai:'นิล',romanizations:['nin','nil'],meaning:'sapphire / dark blue gem',emoji:'💎',level:'medium',lessonId:'medium-9',consonants:['น','ล'],vowels:['ิ'],rules:['final-consonant'],explanation:'น + ิ + final ล→n. After ล and final map (medium-9+).'},
  {id:'nii',thai:'นี้',romanizations:['nii'],meaning:'this',emoji:'👆',level:'advanced',lessonId:'advanced-2',consonants:['น'],vowels:['ี','้'],rules:['open-syllable','tone-mark'],explanation:'นี้ = this. Tone mark ้.'},
  {id:'ki',thai:'กิโล',romanizations:['ki-loo','kilo','gilo'],meaning:'kilo',emoji:'⚖️',level:'basic',lessonId:'basic-9',consonants:['ก','ล'],vowels:['ิ','โ-'],rules:['vowel-before','open-syllable'],explanation:'กิ + โล = kilo.'},
  {id:'kii',thai:'กี่',romanizations:['kii','gii'],meaning:'how many',emoji:'🔢',level:'advanced',lessonId:'advanced-2',consonants:['ก'],vowels:['ี','่'],rules:['open-syllable','tone-mark'],explanation:'กี่ = how many.'},
  {id:'ke',thai:'เกะ',romanizations:['ke','ge'],meaning:'jutting / awkward (เกะกะ)',emoji:'🧩',level:'basic',lessonId:'basic-5',consonants:['ก'],vowels:['เ-','ะ'],rules:['vowel-before','open-syllable','compound-short-e'],explanation:'เ-ะ = one short e. เกะ = ke/ge — not “kea”.'},
  {id:'me',thai:'เมน',romanizations:['men'],meaning:'main (course) / menu clip',emoji:'📋',level:'medium',lessonId:'medium-1',consonants:['ม','น'],vowels:['เ-'],rules:['vowel-before','final-consonant'],explanation:'เ + ม + final น = men.'},
  {id:'ne',thai:'เนย',romanizations:['noei','neoy','ney'],meaning:'butter',emoji:'🧈',level:'medium',lessonId:'medium-2',consonants:['น','ย'],vowels:['เ-'],rules:['vowel-before'],explanation:'เ + น + ย = noei.'},
  {id:'paa',thai:'ปา',romanizations:['bpaa','paa'],meaning:'throw',emoji:'🥏',level:'basic',lessonId:'basic-6',consonants:['ป'],vowels:['า'],rules:['open-syllable'],explanation:'ป = bp/p, า = aa.'},
  {id:'baa',thai:'บา',romanizations:['baa'],meaning:'wound / sore',emoji:'🩹',level:'basic',lessonId:'basic-6',consonants:['บ'],vowels:['า'],rules:['open-syllable'],explanation:'บ = b, า = aa.'},
  {id:'pii',thai:'ปี',romanizations:['bpii','pii'],meaning:'year',emoji:'📅',level:'basic',lessonId:'basic-6',consonants:['ป'],vowels:['ี'],rules:['open-syllable'],explanation:'ป + long ii.'},
  {id:'bii',thai:'บาน',romanizations:['baan'],meaning:'bloom / open (flower)',emoji:'🌸',level:'medium',lessonId:'medium-1',consonants:['บ','น'],vowels:['า'],rules:['final-consonant'],explanation:'บ + า + final น = baan.'},
  {id:'bpe',thai:'เปะ',romanizations:['bpe','pe'],meaning:'smack / splat (onomatopoeic)',emoji:'💥',level:'basic',lessonId:'basic-6',consonants:['ป'],vowels:['เ-','ะ'],rules:['vowel-before','open-syllable','compound-short-e'],explanation:'เ-ะ = short e. เปะ = bpe/pe — not “bpea”.'},
  {id:'be',thai:'เบะ',romanizations:['be'],meaning:'askew / leaning',emoji:'↗️',level:'basic',lessonId:'basic-6',consonants:['บ'],vowels:['เ-','ะ'],rules:['vowel-before','open-syllable','compound-short-e'],explanation:'เ-ะ = short e. เบะ = be — not “bea”.'},
  {id:'ko',thai:'โกะ',romanizations:['ko','go'],meaning:'corner notch (speech; cf. โก่ง)',emoji:'📐',level:'basic',lessonId:'basic-7',consonants:['ก'],vowels:['โ-','ะ'],rules:['vowel-before','open-syllable','compound-short-o'],explanation:'โ-ะ = one short o. โกะ = ko/go — not “koa”.'},
  {id:'mo',thai:'โม',romanizations:['mo'],meaning:'mole (chemistry unit)',emoji:'⚗️',level:'basic',lessonId:'basic-7',consonants:['ม'],vowels:['โ-'],rules:['vowel-before'],explanation:'โ + ม = mo. Contrast with ท.'},
  {id:'no',thai:'โน',romanizations:['no'],meaning:'no (solfège note)',emoji:'🎶',level:'basic',lessonId:'basic-7',consonants:['น'],vowels:['โ-'],rules:['vowel-before'],explanation:'โ + น = no.'},
  {id:'bo',thai:'โบ',romanizations:['bo'],meaning:'bow (gesture; loan clip)',emoji:'🙇',level:'basic',lessonId:'basic-7',consonants:['บ'],vowels:['โ-'],rules:['vowel-before'],explanation:'โ + บ = bo.'},
  {id:'bpo',thai:'โป',romanizations:['bpo','po'],meaning:'po (poster clip / brand form)',emoji:'🪧',level:'basic',lessonId:'basic-7',consonants:['ป'],vowels:['โ-'],rules:['vowel-before'],explanation:'โ + ป = bpo/po.'},
  {id:'kon',thai:'โกน',romanizations:['koon','kon','gon'],meaning:'to shave',emoji:'🪒',level:'medium',lessonId:'medium-1',consonants:['ก','น'],vowels:['โ-'],rules:['vowel-before','final-consonant'],explanation:'โ + ก + final น = kon.'},
  {id:'bpong',thai:'โป่ง',romanizations:['bpong','pong'],meaning:'swollen / puffed',emoji:'🎈',level:'advanced',lessonId:'advanced-2',consonants:['ป','ง'],vowels:['โ-','่'],rules:['vowel-before','final-consonant','tone-mark'],explanation:'โป่ง includes tone mark ่; moved to advanced tone unit.'},
  {id:'taa',thai:'ตา',romanizations:['dtaa','taa'],meaning:'eye / grandfather',emoji:'👁️',level:'basic',lessonId:'basic-8',consonants:['ต'],vowels:['า'],rules:['open-syllable'],explanation:'ต = dt/t, า = aa.'},
  {id:'dto',thai:'โต',romanizations:['dto','to','too'],meaning:'big / grown up',emoji:'🆙',level:'basic',lessonId:'basic-8',consonants:['ต'],vowels:['โ-'],rules:['vowel-before'],explanation:'โ + ต = dto/to.'},
  {id:'dte',thai:'เตะ',romanizations:['dte','te'],meaning:'kick',emoji:'⚽',level:'basic',lessonId:'basic-8',consonants:['ต'],vowels:['เ-','ะ'],rules:['vowel-before','open-syllable','compound-short-e'],explanation:'เ-ะ = short e. เตะ = dte/te — not “dtea”.'},
  {id:'dtii',thai:'ตี',romanizations:['dtii','tii'],meaning:'hit',emoji:'🥊',level:'basic',lessonId:'basic-8',consonants:['ต'],vowels:['ี'],rules:['open-syllable'],explanation:'ต + long ii.'},
  {id:'laa',thai:'ลา',romanizations:['laa'],meaning:'goodbye / take leave',emoji:'👋',level:'basic',lessonId:'basic-9',consonants:['ล'],vowels:['า'],rules:['open-syllable'],explanation:'ล = l, า = aa.'},
  {id:'lo',thai:'โละ',romanizations:['lo'],meaning:'clear out / throw away',emoji:'🗑️',level:'basic',lessonId:'basic-9',consonants:['ล'],vowels:['โ-','ะ'],rules:['vowel-before','open-syllable','compound-short-o'],explanation:'โ-ะ = short o. โละ = lo — not “loa”.'},
  {id:'le',thai:'เละ',romanizations:['le'],meaning:'messy / mushy',emoji:'🫠',level:'basic',lessonId:'basic-9',consonants:['ล'],vowels:['เ-','ะ'],rules:['vowel-before','open-syllable','compound-short-e'],explanation:'เ-ะ = short e. เละ = le — not “lea”.'},
  {id:'raa',thai:'รา',romanizations:['raa'],meaning:'mildew / fungus',emoji:'🦠',level:'basic',lessonId:'basic-9',consonants:['ร'],vowels:['า'],rules:['open-syllable'],explanation:'ร = r, า = aa.'},
  {id:'ro',thai:'รอ',romanizations:['ro'],meaning:'wait',emoji:'⏳',level:'medium',lessonId:'medium-10',consonants:['ร','อ'],vowels:[],rules:['implicit-o','vowel-carrier'],explanation:'ร + อ with implicit o = ro (wait).'},
  {id:'re',thai:'เรอ',romanizations:['roe','reu','re'],meaning:'belch / burp',emoji:'😮‍💨',level:'medium',lessonId:'medium-4',consonants:['ร','อ'],vowels:['เ-'],rules:['vowel-before','vowel-carrier'],explanation:'เ + ร + อ = roe.'},
  {id:'ngaa',thai:'งา',romanizations:['ngaa'],meaning:'sesame',emoji:'🌱',level:'basic',lessonId:'basic-10',consonants:['ง'],vowels:['า'],rules:['open-syllable'],explanation:'ง = ng, า = aa.'},
  {id:'ngii',thai:'งู',romanizations:['nguu'],meaning:'snake',emoji:'🐍',level:'medium',lessonId:'medium-3',consonants:['ง'],vowels:['ู'],rules:['open-syllable'],explanation:'ง + long uu = nguu.'},
  {id:'ngi',thai:'หงิก',romanizations:['ngik'],meaning:'wrinkled / crumpled',emoji:'📉',level:'medium',lessonId:'medium-9',consonants:['ห','ง','ก'],vowels:['ิ'],rules:['final-consonant'],explanation:'หงิก — final ก = k after sound-map review.'},
  {id:'nge',thai:'เงา',romanizations:['ngaao','ngao'],meaning:'shadow',emoji:'🌑',level:'medium',lessonId:'medium-8',consonants:['ง'],vowels:['เ-า'],rules:['vowel-before'],explanation:'เ + ง + า = ngao.'},
  {id:'ngo',thai:'โง่',romanizations:['ngoo','ngo'],meaning:'foolish',emoji:'🤪',level:'advanced',lessonId:'advanced-2',consonants:['ง'],vowels:['โ-','่'],rules:['vowel-before','tone-mark'],explanation:'โง่ = foolish.'},
  {id:'khaa',thai:'คา',romanizations:['khaa'],meaning:'stuck / lodged',emoji:'📌',level:'medium',lessonId:'medium-1',consonants:['ค'],vowels:['า'],rules:['open-syllable'],explanation:'ค = kh (aspirated), า = aa.'},
  {id:'phaa',thai:'พา',romanizations:['phaa'],meaning:'take / bring along',emoji:'🤝',level:'medium',lessonId:'medium-1',consonants:['พ'],vowels:['า'],rules:['open-syllable'],explanation:'พ = ph, า = aa.'},
  {id:'haa',thai:'หา',romanizations:['haa'],meaning:'find / search',emoji:'🔍',level:'medium',lessonId:'medium-1',consonants:['ห'],vowels:['า'],rules:['open-syllable'],explanation:'ห = h, า = aa.'},
  {id:'khii',thai:'คีบ',romanizations:['khiip','khip'],meaning:'tongs / to pinch with tongs',emoji:'🥢',level:'medium',lessonId:'medium-9',consonants:['ค','บ'],vowels:['ี'],rules:['final-consonant'],explanation:'ค + ี + final บ = p (after medium-9 sound map).'},
  {id:'phe',thai:'เพลิน',romanizations:['phloen','pleun'],meaning:'enjoy / be absorbed',emoji:'😊',level:'advanced',lessonId:'advanced-7',consonants:['พ','ล','น'],vowels:['เ-','ิ'],rules:['vowel-before','final-consonant'],explanation:'เพลิน uses an untaught composite reading pattern; moved out of early curriculum until explicitly taught.'},
  {id:'pho',thai:'พอ',romanizations:['pho'],meaning:'enough',emoji:'🆗',level:'medium',lessonId:'medium-10',consonants:['พ','อ'],vowels:[],rules:['implicit-o','vowel-carrier'],explanation:'พ + อ with implicit o = pho (enough).'},
  {id:'waa',thai:'วา',romanizations:['waa'],meaning:'wa (Thai length unit ≈ 2m)',emoji:'📏',level:'medium',lessonId:'medium-2',consonants:['ว'],vowels:['า'],rules:['open-syllable'],explanation:'ว = w, า = aa. วา = Thai fathom.'},
  {id:'yaa',thai:'ยา',romanizations:['yaa'],meaning:'medicine',emoji:'💊',level:'medium',lessonId:'medium-2',consonants:['ย'],vowels:['า'],rules:['open-syllable'],explanation:'ย = y, า = aa.'},
  {id:'jaa',thai:'จาน',romanizations:['jaan'],meaning:'plate / dish',emoji:'🍽️',level:'medium',lessonId:'medium-2',consonants:['จ','น'],vowels:['า'],rules:['final-consonant'],explanation:'จ + า + final น = jaan.'},
  {id:'je',thai:'เจอ',romanizations:['joe','jeu','jer'],meaning:'meet / find',emoji:'🤝',level:'medium',lessonId:'medium-4',consonants:['จ','อ'],vowels:['เ-'],rules:['vowel-before','vowel-carrier'],explanation:'เ + จ + อ = joe.'},
  {id:'jo',thai:'โจ๊ก',romanizations:['jook','joke'],meaning:'rice porridge / congee',emoji:'🍲',level:'advanced',lessonId:'advanced-3',consonants:['จ','ก'],vowels:['โ-','๊'],rules:['vowel-before','final-consonant','tone-mark'],explanation:'โจ๊ก = congee.'},
  {id:'we',thai:'เวร',romanizations:['ween','wen'],meaning:'duty shift / karma',emoji:'🔄',level:'medium',lessonId:'medium-9',consonants:['ว','ร'],vowels:['เ-'],rules:['vowel-before','final-consonant'],explanation:'เ + ว + final ร→n.'},
  {id:'duu',thai:'ดู',romanizations:['duu'],meaning:'look / watch',emoji:'👀',level:'medium',lessonId:'medium-3',consonants:['ด'],vowels:['ู'],rules:['open-syllable'],explanation:'ด = d, ู = uu.'},
  {id:'thaa',thai:'ทา',romanizations:['thaa'],meaning:'apply / spread (cream)',emoji:'🧴',level:'medium',lessonId:'medium-3',consonants:['ท'],vowels:['า'],rules:['open-syllable'],explanation:'ท = th, า = aa.'},
  {id:'chaa',thai:'ชา',romanizations:['chaa'],meaning:'tea',emoji:'🍵',level:'medium',lessonId:'medium-3',consonants:['ช'],vowels:['า'],rules:['open-syllable'],explanation:'ช = ch, า = aa.'},
  {id:'dii',thai:'ดี',romanizations:['dii'],meaning:'good',emoji:'👍',level:'medium',lessonId:'medium-3',consonants:['ด'],vowels:['ี'],rules:['open-syllable'],explanation:'ด + long ii.'},
  {id:'tho',thai:'โท',romanizations:['tho'],meaning:'anger (archaic) / tele-',emoji:'😠',level:'medium',lessonId:'medium-3',consonants:['ท'],vowels:['โ-'],rules:['vowel-before'],explanation:'โ + ท = tho. Contrast with โม.'},
  {id:'che',thai:'เช้า',romanizations:['chaao','chao'],meaning:'morning',emoji:'🌅',level:'advanced',lessonId:'advanced-2',consonants:['ช'],vowels:['เ-','้','า'],rules:['vowel-before','tone-mark'],explanation:'เช้า = morning.'},
  {id:'aa_carrier',thai:'อา',romanizations:['aa'],meaning:'uncle/aunt (younger sibling of a parent)',emoji:'👪',level:'medium',lessonId:'medium-4',consonants:['อ'],vowels:['า'],rules:['open-syllable','vowel-carrier'],explanation:'อา — อ carries long aa.'},
  {id:'o_carrier',thai:'โอ',romanizations:['o'],meaning:'oh! (interjection)',emoji:'😮',level:'medium',lessonId:'medium-4',consonants:['อ'],vowels:['โ-'],rules:['vowel-before','vowel-carrier'],explanation:'โอ — interjection “oh”.'},
  {id:'e_carrier',thai:'เอ',romanizations:['e'],meaning:'A (letter name) / eh',emoji:'🔤',level:'medium',lessonId:'medium-4',consonants:['อ'],vowels:['เ-'],rules:['vowel-before','vowel-carrier'],explanation:'เอ — vowel carrier + เ.'},
  {id:'ii_carrier',thai:'อี',romanizations:['ii'],meaning:'this (colloquial determiner)',emoji:'👉',level:'medium',lessonId:'medium-4',consonants:['อ'],vowels:['ี'],rules:['open-syllable','vowel-carrier'],explanation:'อี — อ carries long ii.'},
  {id:'gae',thai:'แก',romanizations:['gae','kae'],meaning:'you (informal)',emoji:'🫵',level:'medium',lessonId:'medium-5',consonants:['ก'],vowels:['แ-'],rules:['vowel-before'],explanation:'แ + ก = gae/kae.'},
  {id:'mae',thai:'แม่',romanizations:['mae'],meaning:'mother',emoji:'👩',level:'advanced',lessonId:'advanced-2',consonants:['ม'],vowels:['แ-','่'],rules:['vowel-before','tone-mark'],explanation:'แม่ = mother.'},
  {id:'nae',thai:'แนน',romanizations:['naen'],meaning:'Nan (nickname) / tight fit clip',emoji:'😊',level:'medium',lessonId:'medium-5',consonants:['น','น'],vowels:['แ-'],rules:['vowel-before','final-consonant'],explanation:'แ + น + final น = naen.'},
  {id:'phae',thai:'แพ',romanizations:['phae'],meaning:'raft',emoji:'🛶',level:'medium',lessonId:'medium-5',consonants:['พ'],vowels:['แ-'],rules:['vowel-before'],explanation:'แ + พ = phae (raft).'},
  {id:'bae',thai:'แบก',romanizations:['baek'],meaning:'carry on the shoulder',emoji:'🏋️',level:'medium',lessonId:'medium-5',consonants:['บ','ก'],vowels:['แ-'],rules:['vowel-before','final-consonant'],explanation:'แ + บ + final ก = baek.'},
  {id:'lae',thai:'และ',romanizations:['lae'],meaning:'and',emoji:'➕',level:'medium',lessonId:'medium-5',consonants:['ล'],vowels:['แ-','ะ'],rules:['vowel-before','open-syllable'],explanation:'และ = and.'},
  {id:'mu',thai:'มุก',romanizations:['muk'],meaning:'joke / punchline / pearl',emoji:'😄',level:'medium',lessonId:'medium-9',consonants:['ม','ก'],vowels:['ุ'],rules:['final-consonant'],explanation:'ม + ุ + final ก = muk.'},
  {id:'muu',thai:'หมู',romanizations:['muu'],meaning:'pig / pork',emoji:'🐷',level:'medium',lessonId:'medium-6',consonants:['ห','ม'],vowels:['ู'],rules:['open-syllable'],explanation:'หมู = pig. ห + ม + uu.'},
  {id:'nu',thai:'นุ่ง',romanizations:['nung'],meaning:'to put on (lower garment)',emoji:'👖',level:'medium',lessonId:'medium-6',consonants:['น','ง'],vowels:['ุ'],rules:['final-consonant'],explanation:'น + ุ + final ง = nung.'},
  {id:'nuu',thai:'หนู',romanizations:['nuu'],meaning:'mouse / rat; affectionate “you”',emoji:'🐭',level:'medium',lessonId:'medium-6',consonants:['ห','น'],vowels:['ู'],rules:['open-syllable'],explanation:'หนู = mouse.'},
  {id:'pu',thai:'ปุ่ม',romanizations:['bpum','pum'],meaning:'button',emoji:'🔘',level:'medium',lessonId:'medium-6',consonants:['ป','ม'],vowels:['ุ'],rules:['final-consonant'],explanation:'ป + ุ + final ม = bpum.'},
  {id:'puu',thai:'ปู',romanizations:['bpuu','puu'],meaning:'crab',emoji:'🦀',level:'medium',lessonId:'medium-6',consonants:['ป'],vowels:['ู'],rules:['open-syllable'],explanation:'ป + long uu.'},
  {id:'bpai',thai:'ไป',romanizations:['bpai','pai'],meaning:'go',emoji:'🚶',level:'medium',lessonId:'medium-7',consonants:['ป'],vowels:['ไ-'],rules:['vowel-before'],explanation:'ไ + ป = bpai.'},
  {id:'gai',thai:'ไก',romanizations:['gai','kai'],meaning:'gai (clip of ไก่ chicken)',emoji:'🐔',level:'medium',lessonId:'medium-7',consonants:['ก'],vowels:['ไ-'],rules:['vowel-before'],explanation:'ไ + ก = gai. Full ไก่ uses tone ่.'},
  {id:'mai',thai:'ไมล์',romanizations:['mai','mail'],meaning:'mile',emoji:'🛣️',level:'advanced',lessonId:'advanced-6',consonants:['ม','ล'],vowels:['ไ-','์'],rules:['vowel-before','silent-mark'],explanation:'ไมล์ = mile.'},
  {id:'bai',thai:'ใบ',romanizations:['bai'],meaning:'leaf / sheet',emoji:'🍃',level:'medium',lessonId:'medium-7',consonants:['บ'],vowels:['ใ-'],rules:['vowel-before'],explanation:'ใ + บ = bai.'},
  {id:'jai',thai:'ใจ',romanizations:['jai'],meaning:'heart / mind',emoji:'❤️',level:'medium',lessonId:'medium-7',consonants:['จ'],vowels:['ใ-'],rules:['vowel-before'],explanation:'ใ + จ = jai.'},
  {id:'mao',thai:'เมา',romanizations:['mao'],meaning:'drunk',emoji:'🥴',level:'medium',lessonId:'medium-8',consonants:['ม'],vowels:['เ-า'],rules:['vowel-before'],explanation:'เ + ม + า = mao.'},
  {id:'bao',thai:'เบา',romanizations:['bao'],meaning:'light / gentle',emoji:'🪶',level:'medium',lessonId:'medium-8',consonants:['บ'],vowels:['เ-า'],rules:['vowel-before'],explanation:'เ + บ + า = bao.'},
  {id:'rao',thai:'เรา',romanizations:['rao'],meaning:'we / us',emoji:'👥',level:'medium',lessonId:'medium-8',consonants:['ร'],vowels:['เ-า'],rules:['vowel-before'],explanation:'เ + ร + า = rao.'},
  {id:'ao',thai:'เอา',romanizations:['ao'],meaning:'take / want',emoji:'🫴',level:'medium',lessonId:'medium-8',consonants:['อ'],vowels:['เ-า'],rules:['vowel-before','vowel-carrier'],explanation:'เ + อ + า = ao.'},
  {id:'maak',thai:'มาก',romanizations:['maak'],meaning:'very / much',emoji:'📈',level:'medium',lessonId:'medium-1',consonants:['ม','ก'],vowels:['า'],rules:['final-consonant'],explanation:'ม + า + final ก = maak. Final ก = k.'},
  {id:'gin',thai:'กิน',romanizations:['gin','kin'],meaning:'eat',emoji:'🍽️',level:'medium',lessonId:'medium-1',consonants:['ก','น'],vowels:['ิ'],rules:['final-consonant'],explanation:'ก + ิ + final น = gin.'},
  {id:'bpaak',thai:'ปาก',romanizations:['bpaak','paak'],meaning:'mouth',emoji:'👄',level:'medium',lessonId:'medium-1',consonants:['ป','ก'],vowels:['า'],rules:['final-consonant'],explanation:'ป + า + final ก = bpaak.'},
  {id:'naan',thai:'นาน',romanizations:['naan'],meaning:'long (time)',emoji:'⏱️',level:'medium',lessonId:'medium-1',consonants:['น','น'],vowels:['า'],rules:['final-consonant'],explanation:'น + า + final น = naan.'},
  {id:'dtaak',thai:'ตาก',romanizations:['dtaak','taak'],meaning:'dry in the sun',emoji:'☀️',level:'medium',lessonId:'medium-2',consonants:['ต','ก'],vowels:['า'],rules:['final-consonant'],explanation:'ต + า + final ก = dtaak.'},
  {id:'jaak',thai:'จาก',romanizations:['jaak'],meaning:'from',emoji:'📤',level:'medium',lessonId:'medium-2',consonants:['จ','ก'],vowels:['า'],rules:['final-consonant'],explanation:'จ + า + final ก = jaak.'},
  {id:'phaan',thai:'พาน',romanizations:['phaan'],meaning:'ceremonial tray',emoji:'🕯️',level:'medium',lessonId:'medium-2',consonants:['พ','น'],vowels:['า'],rules:['final-consonant'],explanation:'พ + า + final น = phaan.'},
  {id:'din',thai:'ดิน',romanizations:['din'],meaning:'soil / earth',emoji:'🌍',level:'medium',lessonId:'medium-3',consonants:['ด','น'],vowels:['ิ'],rules:['final-consonant'],explanation:'ด + ิ + final น = din.'},
  {id:'chaan',thai:'ชาน',romanizations:['chaan'],meaning:'veranda / platform',emoji:'🏠',level:'medium',lessonId:'medium-3',consonants:['ช','น'],vowels:['า'],rules:['final-consonant'],explanation:'ช + า + final น = chaan.'},
  {id:'nom',thai:'นม',romanizations:['nom'],meaning:'milk',emoji:'🥛',level:'medium',lessonId:'medium-9',consonants:['น','ม'],vowels:[],rules:['final-consonant','implicit-o'],explanation:'Final ม = m. Implicit o.'},
  {id:'bon',thai:'บน',romanizations:['bon'],meaning:'on / above',emoji:'⬆️',level:'medium',lessonId:'medium-9',consonants:['บ','น'],vowels:[],rules:['final-consonant','implicit-o'],explanation:'Final น = n. Implicit o.'},
  {id:'mong',thai:'มอง',romanizations:['mong'],meaning:'look / watch',emoji:'👁️',level:'medium',lessonId:'medium-9',consonants:['ม','ง'],vowels:[],rules:['final-consonant','implicit-o'],explanation:'Final ง = ng. Implicit o.'},
  {id:'khon',thai:'คน',romanizations:['khon'],meaning:'person',emoji:'👤',level:'medium',lessonId:'medium-10',consonants:['ค','น'],vowels:[],rules:['final-consonant','implicit-o'],explanation:'Implicit o between ค and น.'},
  {id:'jon',thai:'จน',romanizations:['jon'],meaning:'until / poor',emoji:'🔚',level:'medium',lessonId:'medium-10',consonants:['จ','น'],vowels:[],rules:['final-consonant','implicit-o'],explanation:'Implicit o vowel.'},
  {id:'khaa2',thai:'ขา',romanizations:['khaa'],meaning:'leg',emoji:'🦵',level:'advanced',lessonId:'advanced-1',consonants:['ข'],vowels:['า'],rules:['open-syllable'],explanation:'ข = kh (high class).'},
  {id:'sii',thai:'สี',romanizations:['sii'],meaning:'colour',emoji:'🎨',level:'advanced',lessonId:'advanced-1',consonants:['ส'],vowels:['ี'],rules:['open-syllable'],explanation:'ส = s (high class).'},
  {id:'faa',thai:'ฟัน',romanizations:['fan'],meaning:'tooth',emoji:'🦷',level:'advanced',lessonId:'advanced-1',consonants:['ฟ','น'],vowels:[],rules:['final-consonant','implicit-o'],explanation:'ฟ + น with implicit o = fan (tooth).'},
  {id:'saa',thai:'ซา',romanizations:['saa'],meaning:'sa (loan syllable in names/foods)',emoji:'🥟',level:'advanced',lessonId:'advanced-1',consonants:['ซ'],vowels:['า'],rules:['open-syllable'],explanation:'ซ = s. Clip from common foods (ซาลาเปา).'},
  {id:'thaa2',thai:'ถาม',romanizations:['thaam'],meaning:'ask',emoji:'❓',level:'advanced',lessonId:'advanced-1',consonants:['ถ','ม'],vowels:['า'],rules:['final-consonant'],explanation:'ถ + า + final ม = thaam.'},
  {id:'phaa2',thai:'ผา',romanizations:['phaa'],meaning:'cliff',emoji:'⛰️',level:'advanced',lessonId:'advanced-1',consonants:['ผ'],vowels:['า'],rules:['open-syllable'],explanation:'ผ = ph (high class).'},
  {id:'faa2',thai:'ฝา',romanizations:['faa'],meaning:'lid / wall',emoji:'🫙',level:'advanced',lessonId:'advanced-1',consonants:['ฝ'],vowels:['า'],rules:['open-syllable'],explanation:'ฝ = f (high class).'},
  {id:'khaa_tone',thai:'ข้า',romanizations:['khaa'],meaning:'I (archaic/servant) / kill',emoji:'🗡️',level:'advanced',lessonId:'advanced-1',consonants:['ข'],vowels:['า','้'],rules:['tone-mark'],explanation:'ข้า with tone mark.'},
  {id:'suay',thai:'สวย',romanizations:['suay','suai'],meaning:'beautiful',emoji:'✨',level:'advanced',lessonId:'advanced-1',consonants:['ส','ว','ย'],vowels:[],rules:['open-syllable','implicit-o'],explanation:'สวย = beautiful.'},
  {id:'sii_zee',thai:'ซี',romanizations:['sii'],meaning:'C (letter) / series clip',emoji:'©️',level:'advanced',lessonId:'advanced-1',consonants:['ซ'],vowels:['ี'],rules:['open-syllable'],explanation:'ซี — long ii with ซ.'},
  {id:'thung',thai:'ถุง',romanizations:['thung'],meaning:'bag',emoji:'🛍️',level:'advanced',lessonId:'advanced-1',consonants:['ถ','ง'],vowels:['ุ'],rules:['final-consonant'],explanation:'ถุง = bag.'},
  {id:'phii',thai:'ผี',romanizations:['phii'],meaning:'ghost',emoji:'👻',level:'advanced',lessonId:'advanced-1',consonants:['ผ'],vowels:['ี'],rules:['open-syllable'],explanation:'ผี = ghost.'},
  {id:'fon',thai:'ฝน',romanizations:['fon'],meaning:'rain',emoji:'🌧️',level:'advanced',lessonId:'advanced-1',consonants:['ฝ','น'],vowels:[],rules:['final-consonant','implicit-o'],explanation:'ฝน = rain.'},
  {id:'khao',thai:'เขา',romanizations:['khao'],meaning:'he/she / mountain',emoji:'🗻',level:'advanced',lessonId:'advanced-2',consonants:['ข','อ'],vowels:['เ-า'],rules:['vowel-before','vowel-carrier'],explanation:'ข + เ-า = khao.'},
  {id:'khaao',thai:'ข้าว',romanizations:['khaao'],meaning:'rice',emoji:'🍚',level:'advanced',lessonId:'advanced-2',consonants:['ข','ว'],vowels:['า','้'],rules:['tone-mark','final-consonant'],explanation:'ข้าว = rice.'},
  {id:'raan',thai:'ร้าน',romanizations:['raan'],meaning:'shop',emoji:'🏪',level:'advanced',lessonId:'advanced-2',consonants:['ร','น'],vowels:['า','้'],rules:['final-consonant','tone-mark'],explanation:'ร้าน = shop.'},
  {id:'baan',thai:'บ้าน',romanizations:['baan'],meaning:'house',emoji:'🏡',level:'advanced',lessonId:'advanced-2',consonants:['บ','น'],vowels:['า','้'],rules:['final-consonant','tone-mark'],explanation:'บ้าน = house.'},
  {id:'naam',thai:'น้ำ',romanizations:['naam'],meaning:'water',emoji:'💧',level:'advanced',lessonId:'advanced-2',consonants:['น','ม'],vowels:['ำ','้'],rules:['final-consonant','tone-mark','special-vowel'],explanation:'น้ำ = water.'},
  {id:'sawasdee',thai:'สวัสดี',romanizations:['sa-wat-dii','sawasdee'],meaning:'hello',emoji:'🙏',level:'advanced',lessonId:'advanced-2',consonants:['ส','ว','ส','ด'],vowels:['ี'],rules:['multi-syllable','implicit-o'],explanation:'สวัสดี — decode syllable by syllable.'},
  {id:'khopkhun',thai:'ขอบคุณ',romanizations:['khop-khun','khopkhun'],meaning:'thank you',emoji:'💝',level:'advanced',lessonId:'advanced-2',consonants:['ข','บ','ค','น'],vowels:[],rules:['final-consonant','multi-syllable','implicit-o'],explanation:'ขอบคุณ — two closed syllables.'},
  {id:'ahaan',thai:'อาหาร',romanizations:['aa-haan','ahaan'],meaning:'food',emoji:'🍲',level:'advanced',lessonId:'advanced-2',consonants:['อ','ห','ร','น'],vowels:['า'],rules:['vowel-carrier','final-consonant','multi-syllable','implicit-o'],explanation:'อาหาร — three pieces.'},
  {id:'kho',thai:'ขอ',romanizations:['kho'],meaning:'ask / request',emoji:'🙏',level:'advanced',lessonId:'advanced-2',consonants:['ข','อ'],vowels:[],rules:['vowel-carrier','implicit-o'],explanation:'ขอ = ask.'},
  {id:'som',thai:'ส้ม',romanizations:['som'],meaning:'orange (fruit)',emoji:'🍊',level:'advanced',lessonId:'advanced-2',consonants:['ส','ม'],vowels:['้'],rules:['final-consonant','tone-mark','implicit-o'],explanation:'ส้ม = orange.'},
  {id:'maa_dog',thai:'หมา',romanizations:['maa'],meaning:'dog',emoji:'🐶',level:'advanced',lessonId:'advanced-2',consonants:['ห','ม'],vowels:['า'],rules:['open-syllable'],explanation:'หมา = dog.'},
  {id:'ron',thai:'ร้อน',romanizations:['ron'],meaning:'hot',emoji:'🔥',level:'advanced',lessonId:'advanced-2',consonants:['ร','น'],vowels:['โ-','้'],rules:['final-consonant','tone-mark','vowel-before'],explanation:'ร้อน = hot.'},
  {id:'klaang',thai:'กลาง',romanizations:['klaang','klang'],meaning:'middle',emoji:'↔️',level:'advanced',lessonId:'advanced-2',consonants:['ก','ล','ง'],vowels:['า'],rules:['final-consonant'],explanation:'กลาง = middle.'},
  {id:'jing',thai:'จริง',romanizations:['jing'],meaning:'true / really',emoji:'✅',level:'advanced',lessonId:'advanced-2',consonants:['จ','ร','ง'],vowels:['ิ'],rules:['final-consonant'],explanation:'จริง = true.'},
  {id:'card_mid',thai:'ก',romanizations:['mid'],meaning:'mid-class consonant (ก)',emoji:'🔤',level:'advanced',lessonId:'advanced-4',consonants:['ก'],vowels:[],rules:['consonant-class'],explanation:'ก is mid class.'},
  {id:'card_high',thai:'ส',romanizations:['high'],meaning:'high-class consonant (ส)',emoji:'🔤',level:'advanced',lessonId:'advanced-4',consonants:['ส'],vowels:[],rules:['consonant-class'],explanation:'ส is high class.'},
  {id:'card_low',thai:'ค',romanizations:['low'],meaning:'low-class consonant (ค)',emoji:'🔤',level:'advanced',lessonId:'advanced-4',consonants:['ค'],vowels:[],rules:['consonant-class'],explanation:'ค is low class.'},
  {id:'tone_ek',thai:'ม่า',romanizations:['maa'],meaning:'low-tone example (mai ek)',emoji:'📉',level:'advanced',lessonId:'advanced-3',consonants:['ม'],vowels:['า','่'],rules:['tone-mark'],explanation:'่ = mai ek.'},
  {id:'tone_tho',thai:'ม้า',romanizations:['maa'],meaning:'horse (falling tone)',emoji:'🐴',level:'advanced',lessonId:'advanced-3',consonants:['ม'],vowels:['า','้'],rules:['tone-mark'],explanation:'ม้า = horse. ้ = mai tho.'},
  {id:'silent_ex',thai:'เธอร์ม',romanizations:['term'],meaning:'therm- (loan root; silent ์)',emoji:'🌡️',level:'advanced',lessonId:'advanced-6',consonants:['ท','ม'],vowels:['เ-','อ','์'],rules:['silent-mark'],explanation:'์ makes preceding letter silent.'},
  {id:'fim',thai:'ฟิล์ม',romanizations:['fim','film'],meaning:'film',emoji:'🎞️',level:'advanced',lessonId:'advanced-6',consonants:['ฟ','ม'],vowels:['ิ','์'],rules:['silent-mark','final-consonant'],explanation:'ฟิล์ม — silent ์.'},
  {id:'gaafae',thai:'กาแฟ',romanizations:['gaafae','kaafae'],meaning:'coffee',emoji:'☕',level:'advanced',lessonId:'advanced-7',consonants:['ก','ฟ'],vowels:['า','แ-'],rules:['vowel-before','multi-syllable'],explanation:'กา + แฟ = coffee.'},
  {id:'thanon',thai:'ถนน',romanizations:['tha-non','thanon'],meaning:'road',emoji:'🛣️',level:'advanced',lessonId:'advanced-7',consonants:['ถ','น','น'],vowels:[],rules:['final-consonant','implicit-o','multi-syllable'],explanation:'ถนน = road.'},
  {id:'roongraem',thai:'โรงแรม',romanizations:['roong-raem','roongraem'],meaning:'hotel',emoji:'🏨',level:'advanced',lessonId:'advanced-7',consonants:['ร','ง','ร','ม'],vowels:['โ-','แ-'],rules:['vowel-before','final-consonant','multi-syllable'],explanation:'โรง + แรม = hotel.'},
  {id:'bpeert',thai:'เปิด',romanizations:['bpeert','pert','peert'],meaning:'open',emoji:'🔓',level:'advanced',lessonId:'advanced-7',consonants:['ป','ด'],vowels:['เ-'],rules:['vowel-before','final-consonant'],explanation:'เปิด — final ด = t.'},
  {id:'bpit',thai:'ปิด',romanizations:['bpit','pit'],meaning:'closed',emoji:'🔒',level:'advanced',lessonId:'advanced-7',consonants:['ป','ด'],vowels:['ิ'],rules:['final-consonant'],explanation:'ปิด — final ด = t.'},
  {id:'khao2',thai:'เข้า',romanizations:['khao'],meaning:'enter',emoji:'🚪',level:'advanced',lessonId:'advanced-7',consonants:['ข','อ'],vowels:['เ-','้'],rules:['vowel-before','vowel-carrier','tone-mark'],explanation:'เข้า = enter.'},
  {id:'awk',thai:'ออก',romanizations:['awk','ok'],meaning:'exit',emoji:'🚪',level:'advanced',lessonId:'advanced-7',consonants:['อ','ก'],vowels:[],rules:['vowel-carrier','final-consonant','implicit-o'],explanation:'ออก = exit.'},
  {id:'thiang',thai:'เที่ยง',romanizations:['thiang'],meaning:'noon',emoji:'🕛',level:'advanced',lessonId:'advanced-7',consonants:['ท','ย','ง'],vowels:['เ-','ี'],rules:['vowel-before','final-consonant'],explanation:'เที่ยง = noon.'},
  {id:'nakrian',thai:'นักเรียน',romanizations:['nak-rian'],meaning:'student',emoji:'🎓',level:'advanced',lessonId:'advanced-7',consonants:['น','ก','ร','ย','น'],vowels:['ิ','เ-','ี'],rules:['final-consonant','multi-syllable','vowel-before'],explanation:'นักเรียน = student.'},
  {id:'roongrian',thai:'โรงเรียน',romanizations:['roong-rian'],meaning:'school',emoji:'🏫',level:'advanced',lessonId:'advanced-7',consonants:['ร','ง','ร','ย','น'],vowels:['โ-','เ-','ี'],rules:['vowel-before','final-consonant','multi-syllable'],explanation:'โรงเรียน = school.'},
  {id:'maew',thai:'แมว',romanizations:['maew'],meaning:'cat',emoji:'🐱',level:'advanced',lessonId:'advanced-7',consonants:['ม','ว'],vowels:['แ-'],rules:['vowel-before','final-consonant'],explanation:'แมว = cat.'},
  {id:'bplaa',thai:'ปลา',romanizations:['bplaa','plaa'],meaning:'fish',emoji:'🐟',level:'advanced',lessonId:'advanced-7',consonants:['ป','ล'],vowels:['า'],rules:['open-syllable'],explanation:'ปลา = fish.'},
];
const LESSONS = [
  {id:'basic-1',level:'basic',order:1,title:'The Thai syllable core',unlockAfter:null,isBoss:false,
    introduces:{consonants:['ก','ม'],vowels:['า'],rules:['consonant-core','long-aa','open-syllable']},
    teachingCards:[{title:'Thai syllables have a core',body:'Thai syllables are built around a main consonant. Vowels attach around that consonant. Today the vowel is easy: า comes after the consonant and sounds like long aa.'},{title:'Font awareness from day one',body:'The same Thai symbol may look different across fonts. You will learn each symbol in looped and modern fonts from the very beginning.'}],
    examples:['gaa','maa'],practiceWordIds:['gaa','maa']},
  {id:'basic-2',level:'basic',order:2,title:'Add น',unlockAfter:'basic-1',isBoss:false,
    introduces:{consonants:['น'],vowels:[],rules:[]},
    teachingCards:[{title:'Same pattern, new consonant',body:'น = n. Compare น with ม — they look similar in some fonts. Practice telling them apart across all font styles.'}],
    examples:['naa','maa'],practiceWordIds:['naa','maa','gaa']},
  {id:'basic-3',level:'basic',order:3,title:'Short a',unlockAfter:'basic-2',isBoss:false,
    introduces:{consonants:[],vowels:['ะ'],rules:['short-a']},
    teachingCards:[{title:'Vowel length matters',body:'า = long aa. ะ = short a. The small mark makes a big difference. Small marks also vary slightly by font and size.'}],
    examples:['ma','ka','na'],practiceWordIds:['ma','ka','na','maa']},
  {id:'basic-4',level:'basic',order:4,title:'i and ii',unlockAfter:'basic-3',isBoss:false,
    introduces:{consonants:[],vowels:['ิ','ี'],rules:['vowel-above']},
    teachingCards:[{title:'Vowels above consonants',body:'Vowels can be marks above (or below) consonants. Find the consonant first, then the vowel. Small vowel marks must be recognised even in different fonts.'}],
    examples:['mi','mii'],practiceWordIds:['mi','mii','maa','gaa']},
  {id:'basic-5',level:'basic',order:5,title:'Vowel before consonant: เ-',unlockAfter:'basic-4',isBoss:false,
    introduces:{consonants:[],vowels:['เ-'],rules:['vowel-before','compound-short-e']},
    teachingCards:[
      {title:'Visual order ≠ pronunciation order',body:'เ is written before the consonant but pronounced after it. เก is ke/ge, not ek.'},
      {title:'เ-ะ is one short e — not “ea”',body:'You already know ะ alone = short a (กะ = ka). When เ and ะ wrap the same consonant, they fuse into one short e. เกะ = ke/ge. Never add an extra “a”: it is not “kea” or “lea”.'},
    ],
    examples:['ke'],practiceWordIds:['ke','maa','mii','gaa']},
  {id:'basic-6',level:'basic',order:6,title:'Add ป and บ',unlockAfter:'basic-5',isBoss:false,
    introduces:{consonants:['ป','บ'],vowels:[],rules:[]},
    teachingCards:[{title:'Similar-looking consonants',body:'ป = bp/p (unaspirated) and บ = b. These are visually similar — บ vs ป is an important font-sensitive distinction.'}],
    examples:['paa','baa','bpe'],practiceWordIds:['paa','baa','bpe','be']},
  {id:'basic-7',level:'basic',order:7,title:'Vowel before consonant: โ-',unlockAfter:'basic-6',isBoss:false,
    introduces:{consonants:[],vowels:['โ-'],rules:['compound-short-o']},
    teachingCards:[
      {title:'โ works like เ',body:'โ is written before the consonant but pronounced after it, just like เ. โม = mo.'},
      {title:'โ-ะ is one short o — not “oa”',body:'Same fusion as เ-ะ: โ + ะ around a consonant = one short o. โกะ = ko/go — not “koa”.'},
    ],
    examples:['ko','mo','bo'],practiceWordIds:['ko','mo','bo','bpo']},
  {id:'basic-8',level:'basic',order:8,title:'Add ต',unlockAfter:'basic-7',isBoss:false,
    introduces:{consonants:['ต'],vowels:[],rules:[]},
    teachingCards:[{title:'Now โต is allowed',body:'ต = dt/t. Now that ต is introduced, you can read โต (big). Distinguish ต from already known letters in modern fonts.'}],
    examples:['taa','dto','dte'],practiceWordIds:['taa','dto','dte','dtii']},
  {id:'basic-9',level:'basic',order:9,title:'Add ล and ร',unlockAfter:'basic-8',isBoss:false,
    introduces:{consonants:['ล','ร'],vowels:[],rules:[]},
    teachingCards:[{title:'ล vs ร',body:'ล = l, ร = r (though casual speech may sound like l). Lead with open long vowels (ลา, รา). Short forms เละ / โละ only show up after the เ-ะ / โ-ะ fusion rules from earlier lessons — not “lea” / “loa”.'}],
    examples:['laa','raa'],practiceWordIds:['laa','raa','lo','le']},
  {id:'basic-10',level:'basic',order:10,title:'Add ง',unlockAfter:'basic-9',isBoss:false,
    introduces:{consonants:['ง'],vowels:[],rules:[]},
    teachingCards:[{title:'Syllables starting with ng',body:'Thai can start syllables with ng. Learn ง shape across all fonts now, because stylised ง can become confusing later.'}],
    examples:['ngaa'],practiceWordIds:['ngaa','maa','naa','dto']},
  {id:'basic-boss',level:'basic',order:11,title:'Basic Boss Test',unlockAfter:'basic-10',isBoss:true,bossQuestions:25,bossFonts:['looped','modern','mixed'],
    introduces:{consonants:[],vowels:[],rules:[]},
    teachingCards:[{title:'Basic Boss Test',body:'This test covers all Basic consonants and vowels. You need 85% to pass. Includes looped, modern, and mixed fonts.'}],
    examples:[],practiceWordIds:['gaa','maa','naa','mii','dto','ngaa','paa','baa','laa','raa']},
  {id:'medium-1',level:'medium',order:12,title:'Add ค พ ห + closed syllables',unlockAfter:'basic-boss',isBoss:false,
    introduces:{consonants:['ค','พ','ห'],vowels:[],rules:['aspirated','final-consonant']},
    teachingCards:[
      {title:'Aspirated consonants',body:'ค = kh and พ = ph are aspirated — not the same as ก and ป. The extra air makes a different sound.'},
      {title:'Syllables can end with a consonant',body:'Until now you mostly read open syllables (consonant + vowel). Thai also has closed syllables: consonant + vowel + final consonant. มาก = maak (ม + า + ก). From medium onward, expect 2-consonant words in practice and tests.'},
    ],
    examples:['khaa','phaa','maak','gin'],practiceWordIds:['khaa','phaa','haa','maak','gin','bpaak','naan']},
  {id:'medium-2',level:'medium',order:13,title:'Add ว ย จ',unlockAfter:'medium-1',isBoss:false,
    introduces:{consonants:['ว','ย','จ'],vowels:[],rules:[]},
    teachingCards:[{title:'Three more consonants',body:'ว = w, ย = y, จ = j. Compare ง vs จ when both are known. Keep practising closed syllables too — จาก, ตาก.'}],
    examples:['waa','jaa','jaak','dtaak'],practiceWordIds:['waa','yaa','jaa','jaak','dtaak','phaan']},
  {id:'medium-3',level:'medium',order:14,title:'Add ด ท ช and ู',unlockAfter:'medium-2',isBoss:false,
    introduces:{consonants:['ด','ท','ช'],vowels:['ู'],rules:[]},
    confusingPairIds:['mo-tho'],
    teachingCards:[
      {title:'New consonants and long uu',body:'ด = d, ท = th, ช = ch. ู = long uu (written below the consonant). Now you can read ดู (look/watch). Closed practice here uses finals that keep their sound: ดิน (din), ชาน (chaan).'},
      {title:'Critical: ม vs ท',body:'ท is new — and it looks a lot like ม (m) you already know. Pause on the contrast slide and memorise the notch on ท. Tests will check this pair often.'},
    ],
    examples:['thaa','tho','duu','din'],practiceWordIds:['thaa','tho','maa','mo','duu','chaan','din','ngii']},
  {id:'medium-4',level:'medium',order:15,title:'Add อ as vowel carrier',unlockAfter:'medium-3',isBoss:false,
    introduces:{consonants:['อ'],vowels:[],rules:['vowel-carrier']},
    teachingCards:[{title:'อ as vowel carrier',body:'อ can support a vowel when there is no other consonant. อา = aa, อี = ii, เอ = e, โอ = o.'}],
    examples:['aa_carrier','ii_carrier','e_carrier','o_carrier'],practiceWordIds:['aa_carrier','ii_carrier','e_carrier','o_carrier']},
  {id:'medium-5',level:'medium',order:16,title:'Add แ-',unlockAfter:'medium-4',isBoss:false,
    introduces:{consonants:[],vowels:['แ-'],rules:[]},
    teachingCards:[{title:'The แ- vowel',body:'แ- = ae sound, written before the consonant like เ- and โ-.'}],
    examples:['gae','phae','lae'],practiceWordIds:['gae','phae','bae','lae','nae']},
  {id:'medium-6',level:'medium',order:17,title:'Add ุ',unlockAfter:'medium-5',isBoss:false,
    introduces:{consonants:[],vowels:['ุ'],rules:['vowel-below']},
    teachingCards:[{title:'Short u below',body:'ุ = short u, written below the consonant. Pair with ู = long uu.'}],
    examples:['muu','nu','puu'],practiceWordIds:['muu','nu','puu','pu']},
  {id:'medium-7',level:'medium',order:18,title:'Add ไ- and ใ-',unlockAfter:'medium-6',isBoss:false,
    introduces:{consonants:[],vowels:['ไ-','ใ-'],rules:[]},
    teachingCards:[{title:'Two ways to write ai',body:'ไ and ใ both sound like ai. ใ is used only in a limited set of words (~20). ไ vs ใ must be recognised visually.'}],
    examples:['bpai','gai','bai','jai'],practiceWordIds:['bpai','gai','bai','jai','mao']},
  {id:'medium-8',level:'medium',order:19,title:'Add เ-า',unlockAfter:'medium-7',isBoss:false,
    introduces:{consonants:[],vowels:['เ-า'],rules:[]},
    teachingCards:[{title:'The ao vowel',body:'เ + า together make the ao sound. เมา = mao (drunk), เรา = rao (we).'}],
    examples:['mao','bao','rao','ao'],practiceWordIds:['mao','bao','rao','ao']},
  {id:'medium-9',level:'medium',order:20,title:'Final consonants deep dive',unlockAfter:'medium-8',isBoss:false,
    introduces:{consonants:[],vowels:[],rules:[]},
    teachingCards:[{title:'Final sounds — map them',body:'Until now closed practice mostly used น ม ง (sound stays n/m/ng) and ก as k. New rule: some finals change sound — ด/ต → t, บ/ป → p. You will meet ปิด (bpit) later. Next lesson adds the hidden short o.'}],
    examples:['maak','gin','nom','bon','mong'],practiceWordIds:['maak','gin','nom','bon','mong']},
  {id:'medium-10',level:'medium',order:21,title:'Implicit short o',unlockAfter:'medium-9',isBoss:false,
    introduces:{consonants:[],vowels:[],rules:['implicit-o']},
    teachingCards:[{title:'Hidden vowel o',body:'If two consonants appear without a written vowel, Thai often inserts a short o. นม = nom (milk), คน = khon (person).'}],
    examples:['nom','bon','khon','jon'],practiceWordIds:['nom','bon','khon','jon']},
  {id:'medium-boss',level:'medium',order:22,title:'Medium Boss Test',unlockAfter:'medium-10',isBoss:true,bossQuestions:35,bossFonts:['looped','modern','mixed'],
    introduces:{consonants:[],vowels:[],rules:[]},
    teachingCards:[{title:'Medium Boss Test',body:'Covers all Basic and Medium material. All font modes. Need 85% to pass.'}],
    examples:[],practiceWordIds:['duu','chaa','bpai','jai','maak','nom','khon','phaa','yaa']},
  {id:'advanced-1',level:'advanced',order:23,title:'More common consonants',unlockAfter:'medium-boss',isBoss:false,
    introduces:{consonants:['ข','ส','ฟ','ซ','ถ','ผ','ฝ'],vowels:[],rules:[]},
    teachingCards:[{title:'Seven new consonants',body:'ข=kh, ส=s, ฟ=f, ซ=s, ถ=th, ผ=ph, ฝ=f. Watch for confusing pairs: ข vs ช, พ vs ฟ, ก vs ถ.'}],
    examples:['khaa2','sii','faa','saa'],practiceWordIds:['khaa2','sii','faa','saa','thaa2']},
  {id:'advanced-2',level:'advanced',order:24,title:'Common real-world words',unlockAfter:'advanced-1',isBoss:false,
    introduces:{consonants:[],vowels:['ำ','้'],rules:['tone-mark','special-vowel','multi-syllable']},
    teachingCards:[
      {title:'Real words with tone marks',body:'Tone mark ้ affects tone. ำ is a special vowel form. Full tone rules come later — for now, identify the mark and continue decoding.'},
      {title:'Longer words = syllable chains',body:'From advanced onward you will read words with 3+ consonants. Decode one syllable at a time: สวัสดี, ขอบคุณ, อาหาร. Do not try to swallow the whole word at once.'},
    ],
    examples:['khao','khaao','raan','sawasdee','khopkhun'],practiceWordIds:['khao','khaao','raan','baan','naam','sawasdee','khopkhun','ahaan','klaang','jing']},
  {id:'advanced-3',level:'advanced',order:25,title:'Tone marks overview',unlockAfter:'advanced-2',isBoss:false,
    introduces:{consonants:[],vowels:['่','๊','๋'],rules:['tone-mark']},
    teachingCards:[{title:'Four tone marks',body:'่ mai ek, ้ mai tho, ๊ mai tri, ๋ mai chattawa. Tone marks affect tone but do not replace vowels. Exact tone depends on consonant class — learned next.'}],
    examples:['tone_ek','tone_tho'],practiceWordIds:['tone_ek','tone_tho']},
  {id:'advanced-4',level:'advanced',order:26,title:'Consonant classes simplified',unlockAfter:'advanced-3',isBoss:false,
    introduces:{consonants:[],vowels:[],rules:['consonant-class']},
    teachingCards:[{title:'Three consonant classes',body:'Mid: ก จ ด ต บ ป อ. High: ข ถ ผ ฝ ส ห. Low: ค ง ช ซ ท น พ ฟ ม ย ร ล ว. Class affects tone rules.'}],
    examples:['card_mid','card_high','card_low'],practiceWordIds:['card_mid','card_high','card_low']},
  {id:'advanced-5',level:'advanced',order:27,title:'Live and dead syllables',unlockAfter:'advanced-4',isBoss:false,
    introduces:{consonants:[],vowels:[],rules:['live-syllable','dead-syllable']},
    teachingCards:[{title:'Live vs dead',body:'Live syllables end in long vowel or sonorant (n, m, ng, w, y). Dead syllables end in short vowel or k/t/p.'}],
    examples:['maak','nom','gin','bpit'],practiceWordIds:['maak','nom','gin','bpit']},
  {id:'advanced-6',level:'advanced',order:28,title:'Silent mark',unlockAfter:'advanced-5',isBoss:false,
    introduces:{consonants:[],vowels:['์'],rules:['silent-mark']},
    teachingCards:[{title:'The silent mark ์',body:'์ (garan) makes a letter silent, often in loanwords or formal spellings.'}],
    examples:['silent_ex'],practiceWordIds:['silent_ex']},
  {id:'advanced-7',level:'advanced',order:29,title:'Multi-syllable words',unlockAfter:'advanced-6',isBoss:false,
    introduces:{consonants:[],vowels:[],rules:['multi-syllable']},
    teachingCards:[{title:'Long words = syllable chains',body:'Longer Thai words are built from syllables. Decode one syllable at a time. Do not panic at long words.'}],
    examples:['gaafae','thanon','roongraem'],practiceWordIds:['gaafae','thanon','roongraem','bpeert','khao2','nakrian','roongrian','maew','bplaa']},
  {id:'advanced-boss',level:'advanced',order:30,title:'Advanced Boss Test',unlockAfter:'advanced-7',isBoss:true,bossQuestions:50,bossFonts:['looped','modern','mixed'],
    introduces:{consonants:[],vowels:[],rules:[]},
    teachingCards:[{title:'Advanced Boss Test',body:'Final challenge! All material, all font modes. Need 85% to pass.'}],
    examples:[],practiceWordIds:['khao','khaao','baan','naam','gaafae','thanon','bpeert','bpit','sii','khaa2']},
];
