// Thai Reading Quest - Curriculum Data

/** Look-alike consonants that need an explicit contrast slide + forced test items. */
const CONFUSING_PAIRS = [
  {
    id: 'mo-tho',
    a: 'ม', b: 'ท',
    aSound: 'm', bSound: 'th',
    aName: 'mo ma', bName: 'tho thahan',
    tip: 'ม (m) looks more open and rounded. ท (th) has a sharper notch where the curve meets the left stem — like a small “bite.”',
    tellApart: 'Find the notch on ท — that is how you tell them apart.',
    footer: 'Remember: โม = mo · โท = tho — you will be tested on this.',
    compare: [
      {thai: 'มา', roman: 'maa', note: 'ม + า'},
      {thai: 'ทา', roman: 'thaa', note: 'ท + า'},
      {thai: 'โม', roman: 'mo', note: 'โ + ม'},
      {thai: 'โท', roman: 'tho', note: 'โ + ท'},
    ],
    wordsA: ['maa', 'mo'],
    wordsB: ['thaa', 'tho'],
    knownAs: { consonants: ['ม', 'ท'] },
    introducedIn: 'medium-3',
  },
  {
    id: 'o-mai-muan',
    a: 'อ', b: 'ใ',
    aSound: '(carrier / o)', bSound: 'ai',
    aName: 'o ang', bName: 'mai muan',
    tip: 'อ is the round “o-shaped” carrier. ใ (mai muan) looks similar but has a crest/whisker on top — that mark means ai, not a silent carrier.',
    tellApart: 'Look for the crest on ใ — if it is missing, you are looking at อ.',
    footer: 'Remember: อา = aa · ใจ = jai — you will be tested on this.',
    compare: [
      {thai: 'อา', roman: 'aa', note: 'อ carrier + า'},
      {thai: 'ใจ', roman: 'jai', note: 'ใ + จ'},
      {thai: 'โอ', roman: 'o', note: 'โ + อ'},
      {thai: 'ใบ', roman: 'bai', note: 'ใ + บ'},
    ],
    wordsA: ['aa_carrier', 'o_carrier'],
    wordsB: ['jai', 'bai'],
    knownAs: { consonants: ['อ'], vowels: ['ใ-'] },
    introducedIn: 'medium-7',
  },
];

const SYMBOLS = [
  {symbol:'ก',type:'consonant',sound:'k/g',introducedIn:'basic-1',warning:'Learners may hear this between English k and g.',exampleWordId:'gaa',role:'consonant'},
  {symbol:'ม',type:'consonant',sound:'m',introducedIn:'basic-1',exampleWordId:'maa',role:'consonant'},
  {symbol:'า',type:'vowel',sound:'aa',introducedIn:'basic-1',role:'long vowel written after the consonant',exampleWordId:'maa'},
  {symbol:'น',type:'consonant',sound:'n',introducedIn:'basic-2',exampleWordId:'naa',role:'consonant'},
  {symbol:'ะ',type:'vowel',sound:'a',introducedIn:'basic-3',role:'short vowel',exampleWordId:'ka'},
  {symbol:'ิ',type:'vowel',sound:'i',introducedIn:'basic-4',role:'short vowel above consonant',exampleWordId:'mi'},
  {symbol:'ี',type:'vowel',sound:'ii',introducedIn:'basic-4',role:'long vowel above consonant',exampleWordId:'mii'},
  {symbol:'เ-',type:'vowel',sound:'e',introducedIn:'basic-5',role:'vowel written before consonant',exampleWordId:'ke',warning:'Written before the consonant but pronounced after it. With ะ it forms one short e (เ-ะ), not “e” + “a”.'},
  {symbol:'ป',type:'consonant',sound:'bp/p',introducedIn:'basic-6',exampleWordId:'paa',role:'consonant',warning:'Unaspirated p — different from บ.'},
  {symbol:'บ',type:'consonant',sound:'b',introducedIn:'basic-6',exampleWordId:'baa',role:'consonant',warning:'Similar to ป — watch the loop at bottom.'},
  {symbol:'โ-',type:'vowel',sound:'o',introducedIn:'basic-7',role:'vowel written before consonant',exampleWordId:'ko',warning:'With ะ it forms one short o (โ-ะ), not “o” + “a”.'},
  {symbol:'ต',type:'consonant',sound:'dt/t',introducedIn:'basic-8',exampleWordId:'taa',role:'consonant'},
  {symbol:'ล',type:'consonant',sound:'l',introducedIn:'basic-9',exampleWordId:'laa',role:'consonant'},
  {symbol:'ร',type:'consonant',sound:'r',introducedIn:'basic-9',exampleWordId:'raa',role:'consonant',warning:'Can sound like l in casual speech.'},
  {symbol:'ง',type:'consonant',sound:'ng',introducedIn:'basic-10',exampleWordId:'ngaa',role:'consonant'},
  {symbol:'ค',type:'consonant',sound:'kh',introducedIn:'medium-1',exampleWordId:'khaa',role:'consonant',warning:'Aspirated — not the same as ก.'},
  {symbol:'พ',type:'consonant',sound:'ph',introducedIn:'medium-1',exampleWordId:'phaa',role:'consonant'},
  {symbol:'ห',type:'consonant',sound:'h',introducedIn:'medium-1',exampleWordId:'haa',role:'consonant'},
  {symbol:'ว',type:'consonant',sound:'w',introducedIn:'medium-2',exampleWordId:'waa',role:'consonant'},
  {symbol:'ย',type:'consonant',sound:'y',introducedIn:'medium-2',exampleWordId:'yaa',role:'consonant'},
  {symbol:'จ',type:'consonant',sound:'j',introducedIn:'medium-2',exampleWordId:'jaan',role:'consonant'},
  {symbol:'ด',type:'consonant',sound:'d',introducedIn:'medium-3',exampleWordId:'duu',role:'consonant'},
  {symbol:'ท',type:'consonant',sound:'th',introducedIn:'medium-3',exampleWordId:'thaa',role:'consonant',warning:'Easy to confuse with ม (m) in modern fonts — watch the notch on ท.'},
  {symbol:'ช',type:'consonant',sound:'ch',introducedIn:'medium-3',exampleWordId:'chaa',role:'consonant'},
  {symbol:'ู',type:'vowel',sound:'uu',introducedIn:'medium-3',role:'long vowel below consonant',exampleWordId:'duu'},
  {symbol:'อ',type:'consonant',sound:'(silent carrier)',introducedIn:'medium-4',exampleWordId:'aa_carrier',role:'vowel carrier / glottal onset',warning:'After a consonant with เ- (เจอ), อ completes the oe/er vowel — it is not silent there.'},
  {symbol:'เ-อ',type:'vowel',sound:'oe/er',introducedIn:'medium-4',role:'compound vowel: เ + consonant + อ',exampleWordId:'je',warning:'Read as oe/er (เจอ = joe). Do not treat อ as a silent leftover letter.'},
  {symbol:'แ-',type:'vowel',sound:'ae',introducedIn:'medium-5',role:'vowel written before consonant',exampleWordId:'gae'},
  {symbol:'ุ',type:'vowel',sound:'u',introducedIn:'medium-6',role:'short vowel below consonant',exampleWordId:'mum'},
  {symbol:'ไ-',type:'vowel',sound:'ai',introducedIn:'medium-7',role:'vowel written before consonant',exampleWordId:'bpai'},
  {symbol:'ใ-',type:'vowel',sound:'ai',introducedIn:'medium-7',role:'vowel — limited usage',exampleWordId:'bai',warning:'Used in only ~20 common words.'},
  {symbol:'เ-า',type:'vowel',sound:'ao',introducedIn:'medium-8',role:'combined vowel pattern',exampleWordId:'mao'},
  {symbol:'ข',type:'consonant',sound:'kh',introducedIn:'advanced-1',exampleWordId:'khaa2',role:'consonant'},
  {symbol:'ส',type:'consonant',sound:'s',introducedIn:'advanced-1',exampleWordId:'sii',role:'consonant'},
  {symbol:'ฟ',type:'consonant',sound:'f',introducedIn:'advanced-1',exampleWordId:'fuu',role:'consonant'},
  {symbol:'ซ',type:'consonant',sound:'s',introducedIn:'advanced-1',exampleWordId:'saa',role:'consonant'},
  {symbol:'ถ',type:'consonant',sound:'th',introducedIn:'advanced-1b',exampleWordId:'thaa2',role:'consonant'},
  {symbol:'ผ',type:'consonant',sound:'ph',introducedIn:'advanced-1b',exampleWordId:'phaa2',role:'consonant'},
  {symbol:'ฝ',type:'consonant',sound:'f',introducedIn:'advanced-1b',exampleWordId:'faa2',role:'consonant'},
  {symbol:'ั',type:'vowel',sound:'a',introducedIn:'advanced-1c',role:'short a above consonant (mai han-akat)',exampleWordId:'fan',warning:'Not the same as ะ (after the consonant). ั sits above and usually needs a final consonant — ฟัน = fan.'},
  {symbol:'่',type:'tone mark',sound:'(low tone mark)',introducedIn:'advanced-2',role:'mai ek tone mark'},
  {symbol:'้',type:'tone mark',sound:'(falling tone mark)',introducedIn:'advanced-2',role:'mai tho tone mark'},
  {symbol:'๊',type:'tone mark',sound:'(high tone mark)',introducedIn:'advanced-3',role:'mai tri tone mark'},
  {symbol:'๋',type:'tone mark',sound:'(rising tone mark)',introducedIn:'advanced-3',role:'mai chattawa tone mark'},
  {symbol:'์',type:'special mark',sound:'(silent)',introducedIn:'advanced-6',role:'silent mark / garan'},
  {symbol:'ำ',type:'vowel',sound:'am',introducedIn:'advanced-2',role:'special vowel form',exampleWordId:'naam'},
  {symbol:'-วย',type:'vowel',sound:'uay',introducedIn:'advanced-2',role:'ว as ua vowel + final ย',exampleWordId:'suay',warning:'Here ว is not consonant “w” — with final ย it makes uay. สวย = suay (beautiful).'},
];

/**
 * WORD BANK RULES
 * - Never test letter≠sound exceptions before those rules are taught
 *   (final ด/ต → t, บ/ป → p, ร/ล → n — all gated behind medium-9 `final-sound-map`).
 *   Also gate ั (mai han-akat) and -วย (ว as ua vowel) until those marks/patterns are taught.
 * - Prefer sonorant finals น / ม / ง early; use final ก only as k once closed syllables are taught.
 * - Every word must be a real dictionary form with a real meaning (no “(syllable)” fillers).
 * - `emoji` (1–2) is shown on the answer feedback card with the meaning.
 */
/** Source word definitions — Thai + romanizations compiled by word-spec.js from rules. */
const WORD_SPECS = [
  {id:'gaa',romanAlternates:['kaa','gaa'],meaning:'crow',emoji:'🐦',level:'basic',lessonId:'basic-1',consonants:['ก'],vowels:['า'],rules:['open-syllable'],explanation:'ก = k/g, า = long aa.'},
  {id:'maa',romanAlternates:['maa'],meaning:'come',emoji:'👋',level:'basic',lessonId:'basic-1',consonants:['ม'],vowels:['า'],rules:['open-syllable'],explanation:'ม = m, า = long aa.'},
  {id:'naa',romanAlternates:['naa'],meaning:'field / rice field',emoji:'🌾',level:'basic',lessonId:'basic-2',consonants:['น'],vowels:['า'],rules:['open-syllable'],explanation:'น = n, า = aa.'},
  {id:'ma',thai:'มานะ',romanAlternates:['maana','maa-na'],meaning:'perseverance / determination',emoji:'💪',level:'basic',lessonId:'basic-3',consonants:['ม','น'],vowels:['า','ะ'],rules:['open-syllable'],explanation:'มานะ = maa + na. Short a with ะ.',
    readingUnits:[
      {kind:'consonant',key:'consonant:ม',symbol:'ม',label:'ม = m',thai:'ม',roman:'m',role:'initial'},
      {kind:'vowel',key:'vowel:า',symbols:['า'],label:'า = aa',thai:'◌า',roman:'aa'},
      {kind:'consonant',key:'consonant:น',symbol:'น',label:'น = n',thai:'น',roman:'n',role:'initial'},
      {kind:'vowel',key:'vowel:ะ',symbols:['ะ'],label:'ะ = a',thai:'◌ะ',roman:'a'},
    ]},
  {id:'ka',romanAlternates:['ka','ga'],meaning:'to estimate / a portion',emoji:'⚖️',level:'basic',lessonId:'basic-3',consonants:['ก'],vowels:['ะ'],rules:['open-syllable'],explanation:'Short a vowel.'},
  {id:'na',thai:'นานา',romanAlternates:['naanaa','naa-naa'],meaning:'various / diverse',emoji:'🌈',level:'basic',lessonId:'basic-3',consonants:['น','น'],vowels:['า','า'],rules:['open-syllable'],explanation:'นา + นา — practice น and long aa.',
    readingUnits:[
      {kind:'consonant',key:'consonant:น',symbol:'น',label:'น = n',thai:'น',roman:'n',role:'initial'},
      {kind:'vowel',key:'vowel:า',symbols:['า'],label:'า = aa',thai:'◌า',roman:'aa'},
      {kind:'consonant',key:'consonant:น:2',symbol:'น',label:'น = n',thai:'น',roman:'n',role:'initial'},
      {kind:'vowel',key:'vowel:า:2',symbols:['า'],label:'า = aa',thai:'◌า',roman:'aa'},
    ]},
  {id:'mi',romanAlternates:['mi'],meaning:'not (formal)',emoji:'🚫',level:'basic',lessonId:'basic-4',consonants:['ม'],vowels:['ิ'],rules:['open-syllable'],explanation:'Short i. Formal/literary “not”.'},
  {id:'mii',romanAlternates:['mii'],meaning:'have / there is',emoji:'✅',level:'basic',lessonId:'basic-4',consonants:['ม'],vowels:['ี'],rules:['open-syllable'],explanation:'Long ii above consonant.'},
  {id:'ni',romanAlternates:['nin','nil'],meaning:'sapphire / dark blue gem',emoji:'💎',level:'medium',lessonId:'medium-9',consonants:['น','ล'],vowels:['ิ'],rules:['final-consonant','final-sound-map'],explanation:'น + ิ + final ล→n (not “l”). Final ร/ล sound like n.'},
  {id:'nii',thai:'นี้',romanAlternates:['nii'],meaning:'this',emoji:'👆',level:'advanced',lessonId:'advanced-2',consonants:['น'],vowels:['ี','้'],rules:['open-syllable','tone-mark'],explanation:'นี้ = this. Tone mark ้.'},
  {id:'ki',thai:'กิโล',romanAlternates:['kiloo','kilo','gilo','ki-loo'],meaning:'kilo',emoji:'⚖️',level:'basic',lessonId:'basic-9',consonants:['ก','ล'],vowels:['ิ','โ-'],rules:['vowel-before','open-syllable'],explanation:'กิ + โล = kilo.',
    readingUnits:[
      {kind:'consonant',key:'consonant:ก',symbol:'ก',label:'ก = k/g',thai:'ก',roman:'k',role:'initial'},
      {kind:'vowel',key:'vowel:ิ',symbols:['ิ'],label:'ิ = i',thai:'◌ิ',roman:'i'},
      {kind:'consonant',key:'consonant:ล',symbol:'ล',label:'ล = l',thai:'ล',roman:'l',role:'initial'},
      {kind:'vowel',key:'vowel:โ-',symbols:['โ-'],label:'โ- = oo',thai:'โ◌',roman:'oo'},
    ]},
  {id:'kii',thai:'กี่',romanAlternates:['kii','gii'],meaning:'how many',emoji:'🔢',level:'advanced',lessonId:'advanced-3',consonants:['ก'],vowels:['ี','่'],rules:['open-syllable','tone-mark'],explanation:'กี่ = how many.'},
  {id:'ke',romanAlternates:['ke','ge'],meaning:'jutting / awkward (เกะกะ)',emoji:'🧩',level:'basic',lessonId:'basic-5',consonants:['ก'],vowels:['เ-','ะ'],rules:['vowel-before','open-syllable','compound-short-e'],explanation:'เ-ะ = one short e. เกะ = ke/ge — not “kea”.'},
  {id:'men',romanAlternates:['men'],meaning:'main (course) / menu clip',emoji:'📋',level:'medium',lessonId:'medium-1',consonants:['ม','น'],vowels:['เ-'],rules:['vowel-before','final-consonant'],explanation:'เ + ม + final น = men.'},
  {id:'ne',thai:'เนย',romanAlternates:['noei','neoy','ney','noey'],meaning:'butter',emoji:'🧈',level:'advanced',lessonId:'advanced-7',consonants:['น','ย'],vowels:['เ-'],rules:['vowel-before'],explanation:'เนย uses an untaught composite reading pattern; moved out of early curriculum until explicitly taught.',
    readingUnits:[
      {kind:'consonant',key:'consonant:น',symbol:'น',label:'น = n',thai:'น',roman:'n',role:'initial'},
      {kind:'vowel',key:'vowel:เ-ย',symbols:['เ-','ย'],label:'เ◌ย = oei',thai:'เ◌ย',roman:'oei'},
    ]},
  {id:'paa',romanAlternates:['bpaa','paa'],meaning:'throw',emoji:'🥏',level:'basic',lessonId:'basic-6',consonants:['ป'],vowels:['า'],rules:['open-syllable'],explanation:'ป = bp/p, า = aa.'},
  {id:'baa',romanAlternates:['baa'],meaning:'wound / sore',emoji:'🩹',level:'basic',lessonId:'basic-6',consonants:['บ'],vowels:['า'],rules:['open-syllable'],explanation:'บ = b, า = aa.'},
  {id:'pii',romanAlternates:['bpii','pii'],meaning:'year',emoji:'📅',level:'basic',lessonId:'basic-6',consonants:['ป'],vowels:['ี'],rules:['open-syllable'],explanation:'ป + long ii.'},
  {id:'baan_open',romanAlternates:['baan'],meaning:'bloom / open (flower)',emoji:'🌸',level:'medium',lessonId:'medium-1',consonants:['บ','น'],vowels:['า'],rules:['final-consonant'],explanation:'บ + า + final น = baan.'},
  {id:'bpe',romanAlternates:['bpe','pe'],meaning:'smack / splat (onomatopoeic)',emoji:'💥',level:'basic',lessonId:'basic-6',consonants:['ป'],vowels:['เ-','ะ'],rules:['vowel-before','open-syllable','compound-short-e'],explanation:'เ-ะ = short e. เปะ = bpe/pe — not “bpea”.'},
  {id:'be',romanAlternates:['be'],meaning:'askew / leaning',emoji:'↗️',level:'basic',lessonId:'basic-6',consonants:['บ'],vowels:['เ-','ะ'],rules:['vowel-before','open-syllable','compound-short-e'],explanation:'เ-ะ = short e. เบะ = be — not “bea”.'},
  {id:'ko',romanAlternates:['ko','go'],meaning:'corner notch (speech; cf. โก่ง)',emoji:'📐',level:'basic',lessonId:'basic-7',consonants:['ก'],vowels:['โ-','ะ'],rules:['vowel-before','open-syllable','compound-short-o'],explanation:'โ-ะ = one short o. โกะ = ko/go — not “koa”.'},
  {id:'mo',romanAlternates:['mo'],meaning:'mole (chemistry unit)',emoji:'⚗️',level:'basic',lessonId:'basic-7',consonants:['ม'],vowels:['โ-'],rules:['vowel-before'],explanation:'โ + ม = mo. Contrast with ท.'},
  {id:'no',romanAlternates:['no'],meaning:'no (solfège note)',emoji:'🎶',level:'basic',lessonId:'basic-7',consonants:['น'],vowels:['โ-'],rules:['vowel-before'],explanation:'โ + น = no.'},
  {id:'bo',romanAlternates:['bo'],meaning:'bow (gesture; loan clip)',emoji:'🙇',level:'basic',lessonId:'basic-7',consonants:['บ'],vowels:['โ-'],rules:['vowel-before'],explanation:'โ + บ = bo.'},
  {id:'bpo',romanAlternates:['bpo','po'],meaning:'po (poster clip / brand form)',emoji:'🪧',level:'basic',lessonId:'basic-7',consonants:['ป'],vowels:['โ-'],rules:['vowel-before'],explanation:'โ + ป = bpo/po.'},
  {id:'kon',romanAlternates:['koon','kon','gon'],meaning:'to shave',emoji:'🪒',level:'medium',lessonId:'medium-1',consonants:['ก','น'],vowels:['โ-'],rules:['vowel-before','final-consonant'],explanation:'โ + ก + final น = kon.'},
  {id:'bpong',romanAlternates:['bpong','pong'],meaning:'swollen / puffed',emoji:'🎈',level:'advanced',lessonId:'advanced-3',consonants:['ป','ง'],vowels:['โ-','่'],rules:['vowel-before','final-consonant','tone-mark'],explanation:'โป่ง includes tone mark ่; moved to advanced tone unit.'},
  {id:'taa',romanAlternates:['dtaa','taa'],meaning:'eye / grandfather',emoji:'👁️',level:'basic',lessonId:'basic-8',consonants:['ต'],vowels:['า'],rules:['open-syllable'],explanation:'ต = dt/t, า = aa.'},
  {id:'dto',romanAlternates:['dto','to','too'],meaning:'big / grown up',emoji:'🆙',level:'basic',lessonId:'basic-8',consonants:['ต'],vowels:['โ-'],rules:['vowel-before'],explanation:'โ + ต = dto/to.'},
  {id:'dte',romanAlternates:['dte','te'],meaning:'kick',emoji:'⚽',level:'basic',lessonId:'basic-8',consonants:['ต'],vowels:['เ-','ะ'],rules:['vowel-before','open-syllable','compound-short-e'],explanation:'เ-ะ = short e. เตะ = dte/te — not “dtea”.'},
  {id:'dtii',romanAlternates:['dtii','tii'],meaning:'hit',emoji:'🥊',level:'basic',lessonId:'basic-8',consonants:['ต'],vowels:['ี'],rules:['open-syllable'],explanation:'ต + long ii.'},
  {id:'laa',romanAlternates:['laa'],meaning:'goodbye / take leave',emoji:'👋',level:'basic',lessonId:'basic-9',consonants:['ล'],vowels:['า'],rules:['open-syllable'],explanation:'ล = l, า = aa.'},
  {id:'lo',romanAlternates:['lo'],meaning:'clear out / throw away',emoji:'🗑️',level:'basic',lessonId:'basic-9',consonants:['ล'],vowels:['โ-','ะ'],rules:['vowel-before','open-syllable','compound-short-o'],explanation:'โ-ะ = short o. โละ = lo — not “loa”.'},
  {id:'le',romanAlternates:['le'],meaning:'messy / mushy',emoji:'🫠',level:'basic',lessonId:'basic-9',consonants:['ล'],vowels:['เ-','ะ'],rules:['vowel-before','open-syllable','compound-short-e'],explanation:'เ-ะ = short e. เละ = le — not “lea”.'},
  {id:'raa',romanAlternates:['raa'],meaning:'mildew / fungus',emoji:'🦠',level:'basic',lessonId:'basic-9',consonants:['ร'],vowels:['า'],rules:['open-syllable'],explanation:'ร = r, า = aa.'},
  {id:'ro',romanAlternates:['ro'],meaning:'wait',emoji:'⏳',level:'medium',lessonId:'medium-10',consonants:['ร','อ'],vowels:[],rules:['implicit-o','vowel-carrier'],explanation:'ร + อ with implicit o = ro (wait).'},
  {id:'re',thai:'เรอ',romanAlternates:['roe','reu','re','rer'],meaning:'belch / burp',emoji:'😮‍💨',level:'medium',lessonId:'medium-4',consonants:['ร'],vowels:['เ-','เ-อ'],rules:['vowel-before','vowel-carrier','compound-oe'],explanation:'เ + ร + อ = one oe/er sound (roe). อ completes the vowel — it is not silent.'},
  {id:'ngaa',romanAlternates:['ngaa'],meaning:'sesame',emoji:'🌱',level:'basic',lessonId:'basic-10',consonants:['ง'],vowels:['า'],rules:['open-syllable'],explanation:'ง = ng, า = aa.'},
  {id:'nguu',romanAlternates:['nguu'],meaning:'snake',emoji:'🐍',level:'medium',lessonId:'medium-3',consonants:['ง'],vowels:['ู'],rules:['open-syllable'],explanation:'ง + long uu = nguu.'},
  {id:'ngi',romanAlternates:['ngik'],meaning:'wrinkled / crumpled',emoji:'📉',level:'advanced',lessonId:'advanced-1c',consonants:['ห','ง','ก'],vowels:['ิ'],rules:['final-consonant','leading-h'],explanation:'หงิก: leading ห before ง is silent for reading class; say ngik (not hngik).'},
  {id:'ngao',romanAlternates:['ngao'],meaning:'shadow',emoji:'🌑',level:'medium',lessonId:'medium-8',consonants:['ง'],vowels:['เ-า'],rules:['vowel-before'],explanation:'เ + ง + า = ngao.'},
  {id:'ngo',romanAlternates:['ngoo','ngo'],meaning:'foolish',emoji:'🤪',level:'advanced',lessonId:'advanced-3',consonants:['ง'],vowels:['โ-','่'],rules:['vowel-before','tone-mark'],explanation:'โง่ = foolish.'},
  {id:'khaa',romanAlternates:['khaa'],meaning:'stuck / lodged',emoji:'📌',level:'medium',lessonId:'medium-1',consonants:['ค'],vowels:['า'],rules:['open-syllable'],explanation:'ค = kh (aspirated), า = aa.'},
  {id:'phaa',romanAlternates:['phaa'],meaning:'take / bring along',emoji:'🤝',level:'medium',lessonId:'medium-1',consonants:['พ'],vowels:['า'],rules:['open-syllable'],explanation:'พ = ph, า = aa.'},
  {id:'haa',romanAlternates:['haa'],meaning:'find / search',emoji:'🔍',level:'medium',lessonId:'medium-1',consonants:['ห'],vowels:['า'],rules:['open-syllable'],explanation:'ห = h, า = aa.'},
  {id:'khii',romanAlternates:['khiip','khip'],meaning:'tongs / to pinch with tongs',emoji:'🥢',level:'medium',lessonId:'medium-9',consonants:['ค','บ'],vowels:['ี'],rules:['final-consonant','final-sound-map'],explanation:'ค + ี + final บ→p (not “b”).'},
  {id:'phe',romanAlternates:['phloen','pleun'],meaning:'enjoy / be absorbed',emoji:'😊',level:'advanced',lessonId:'advanced-7',consonants:['พ','ล','น'],vowels:['เ-','ิ'],rules:['vowel-before','final-consonant','compound-oe-i'],explanation:'พ + ล = phl cluster. เ◌ิ = oe (not i). Final น = n → phloen.',
    readingUnits:[
      {kind:'cluster',key:'cluster:พ+ล',symbols:['พ','ล'],label:'พ + ล = phl',thai:'พล',roman:'phl',hint:'Read พ and ล together as phl.'},
      {kind:'vowel',key:'rule:compound-oe-i',rule:'compound-oe-i',symbols:['เ-','ิ'],label:'เ◌ิ = oe (not i)',thai:'เ◌ิ',roman:'oe',hint:'Not e + i — one oe vowel.'},
      {kind:'consonant',key:'consonant:น:final',symbol:'น',label:'น = n (final)',thai:'น',roman:'n',role:'final'},
    ]},
  {id:'pho',romanAlternates:['pho'],meaning:'enough',emoji:'🆗',level:'medium',lessonId:'medium-10',consonants:['พ','อ'],vowels:[],rules:['implicit-o','vowel-carrier'],explanation:'พ + อ with implicit o = pho (enough).'},
  {id:'waa',romanAlternates:['waa'],meaning:'wa (Thai length unit ≈ 2m)',emoji:'📏',level:'medium',lessonId:'medium-2',consonants:['ว'],vowels:['า'],rules:['open-syllable'],explanation:'ว = w, า = aa. วา = Thai fathom.'},
  {id:'yaa',romanAlternates:['yaa'],meaning:'medicine',emoji:'💊',level:'medium',lessonId:'medium-2',consonants:['ย'],vowels:['า'],rules:['open-syllable'],explanation:'ย = y, า = aa.'},
  {id:'jaan',romanAlternates:['jaan'],meaning:'plate / dish',emoji:'🍽️',level:'medium',lessonId:'medium-2',consonants:['จ','น'],vowels:['า'],rules:['final-consonant'],explanation:'จ + า + final น = jaan.'},
  {id:'je',thai:'เจอ',romanAlternates:['joe','jeu','jer','je'],meaning:'meet / find',emoji:'🤝',level:'medium',lessonId:'medium-4',consonants:['จ'],vowels:['เ-','เ-อ'],rules:['vowel-before','vowel-carrier','compound-oe'],explanation:'เ + จ + อ = one oe/er sound (joe). อ completes the vowel — it is not silent.'},
  {id:'jo',romanAlternates:['jook'],meaning:'rice porridge / congee',emoji:'🍲',level:'advanced',lessonId:'advanced-3',consonants:['จ','ก'],vowels:['โ-','๊'],rules:['vowel-before','final-consonant','tone-mark'],explanation:'โจ๊ก = congee.'},
  {id:'we',romanAlternates:['ween','wen'],meaning:'duty shift / karma',emoji:'🔄',level:'medium',lessonId:'medium-9',consonants:['ว','ร'],vowels:['เ-'],rules:['vowel-before','final-consonant','final-sound-map'],explanation:'เ + ว + final ร→n (not “r”). Final ร/ล sound like n.'},
  {id:'duu',romanAlternates:['duu'],meaning:'look / watch',emoji:'👀',level:'medium',lessonId:'medium-3',consonants:['ด'],vowels:['ู'],rules:['open-syllable'],explanation:'ด = d, ู = uu.'},
  {id:'thaa',romanAlternates:['thaa'],meaning:'apply / spread (cream)',emoji:'🧴',level:'medium',lessonId:'medium-3',consonants:['ท'],vowels:['า'],rules:['open-syllable'],explanation:'ท = th, า = aa.'},
  {id:'chaa',romanAlternates:['chaa'],meaning:'tea',emoji:'🍵',level:'medium',lessonId:'medium-3',consonants:['ช'],vowels:['า'],rules:['open-syllable'],explanation:'ช = ch, า = aa.'},
  {id:'dii',romanAlternates:['dii'],meaning:'good',emoji:'👍',level:'medium',lessonId:'medium-3',consonants:['ด'],vowels:['ี'],rules:['open-syllable'],explanation:'ด + long ii.'},
  {id:'tho',romanAlternates:['tho'],meaning:'anger (archaic) / tele-',emoji:'😠',level:'medium',lessonId:'medium-3',consonants:['ท'],vowels:['โ-'],rules:['vowel-before'],explanation:'โ + ท = tho. Contrast with โม.'},
  {id:'che',thai:'เช้า',romanAlternates:['chao'],meaning:'morning',emoji:'🌅',level:'advanced',lessonId:'advanced-2',consonants:['ช'],vowels:['เ-า','้'],rules:['vowel-before','tone-mark'],explanation:'เช้า = morning.'},
  {id:'aa_carrier',romanAlternates:['aa'],meaning:'uncle/aunt (younger sibling of a parent)',emoji:'👪',level:'medium',lessonId:'medium-4',consonants:['อ'],vowels:['า'],rules:['open-syllable','vowel-carrier'],explanation:'อา — อ carries long aa.'},
  {id:'o_carrier',romanAlternates:['o'],meaning:'oh! (interjection)',emoji:'😮',level:'medium',lessonId:'medium-4',consonants:['อ'],vowels:['โ-'],rules:['vowel-before','vowel-carrier'],explanation:'โอ — interjection “oh”.'},
  {id:'e_carrier',romanAlternates:['e'],meaning:'A (letter name) / eh',emoji:'🔤',level:'medium',lessonId:'medium-4',consonants:['อ'],vowels:['เ-'],rules:['vowel-before','vowel-carrier'],explanation:'เอ — vowel carrier + เ.'},
  {id:'ii_carrier',romanAlternates:['ii'],meaning:'this (colloquial determiner)',emoji:'👉',level:'medium',lessonId:'medium-4',consonants:['อ'],vowels:['ี'],rules:['open-syllable','vowel-carrier'],explanation:'อี — อ carries long ii.'},
  {id:'gae',romanAlternates:['gae','kae'],meaning:'you (informal)',emoji:'🫵',level:'medium',lessonId:'medium-5',consonants:['ก'],vowels:['แ-'],rules:['vowel-before'],explanation:'แ + ก = gae/kae.'},
  {id:'mae',romanAlternates:['mae'],meaning:'mother',emoji:'👩',level:'advanced',lessonId:'advanced-3',consonants:['ม'],vowels:['แ-','่'],rules:['vowel-before','tone-mark'],explanation:'แม่ = mother.'},
  {id:'nae',romanAlternates:['naen'],meaning:'Nan (nickname) / tight fit clip',emoji:'😊',level:'medium',lessonId:'medium-5',consonants:['น','น'],vowels:['แ-'],rules:['vowel-before','final-consonant'],explanation:'แ + น + final น = naen.'},
  {id:'phae',romanAlternates:['phae'],meaning:'raft',emoji:'🛶',level:'medium',lessonId:'medium-5',consonants:['พ'],vowels:['แ-'],rules:['vowel-before'],explanation:'แ + พ = phae (raft).'},
  {id:'bae',romanAlternates:['baek'],meaning:'carry on the shoulder',emoji:'🏋️',level:'medium',lessonId:'medium-5',consonants:['บ','ก'],vowels:['แ-'],rules:['vowel-before','final-consonant'],explanation:'แ + บ + final ก = baek.'},
  {id:'lae',thai:'และ',romanAlternates:['lae'],meaning:'and',emoji:'➕',level:'medium',lessonId:'medium-5',consonants:['ล'],vowels:['แ-','ะ'],rules:['vowel-before','open-syllable'],explanation:'และ = and.'},
  {id:'mu',romanAlternates:['muk'],meaning:'joke / punchline / pearl',emoji:'😄',level:'medium',lessonId:'medium-9',consonants:['ม','ก'],vowels:['ุ'],rules:['final-consonant'],explanation:'ม + ุ + final ก = muk.'},
  {id:'muu',romanAlternates:['muu'],meaning:'pig / pork',emoji:'🐷',level:'advanced',lessonId:'advanced-1c',consonants:['ห','ม'],vowels:['ู'],rules:['open-syllable','leading-h'],explanation:'หมู = pig. Leading ห before ม is silent for class; read muu (not hmuu).'},
  {id:'lung',romanAlternates:['lung'],meaning:'uncle (older brother of a parent)',emoji:'👨',level:'medium',lessonId:'medium-6',consonants:['ล','ง'],vowels:['ุ'],rules:['final-consonant'],explanation:'ล + ุ + final ง = lung.'},
  {id:'nuu',romanAlternates:['nuu'],meaning:'mouse / rat; affectionate “you”',emoji:'🐭',level:'advanced',lessonId:'advanced-1c',consonants:['ห','น'],vowels:['ู'],rules:['open-syllable','leading-h'],explanation:'หนู = mouse. Leading ห before น is silent for class; read nuu (not hnuu).'},
  {id:'mum',romanAlternates:['mum'],meaning:'corner / angle',emoji:'📐',level:'medium',lessonId:'medium-6',consonants:['ม','ม'],vowels:['ุ'],rules:['final-consonant'],explanation:'ม + ุ + final ม = mum.'},
  {id:'puu',romanAlternates:['bpuu','puu'],meaning:'crab',emoji:'🦀',level:'medium',lessonId:'medium-6',consonants:['ป'],vowels:['ู'],rules:['open-syllable'],explanation:'ป + long uu.'},
  {id:'bpai',romanAlternates:['bpai','pai'],meaning:'go',emoji:'🚶',level:'medium',lessonId:'medium-7',consonants:['ป'],vowels:['ไ-'],rules:['vowel-before'],explanation:'ไ + ป = bpai.'},
  {id:'gai',romanAlternates:['gai','kai'],meaning:'gai (clip of ไก่ chicken)',emoji:'🐔',level:'medium',lessonId:'medium-7',consonants:['ก'],vowels:['ไ-'],rules:['vowel-before'],explanation:'ไ + ก = gai. Full ไก่ uses tone ่.'},
  {id:'mai',thai:'ไมล์',romanAlternates:['mai','mail'],meaning:'mile',emoji:'🛣️',level:'advanced',lessonId:'advanced-6',consonants:['ม','ล'],vowels:['ไ-','์'],rules:['vowel-before','silent-mark'],explanation:'ไมล์ = mile.'},
  {id:'bai',romanAlternates:['bai'],meaning:'leaf / sheet',emoji:'🍃',level:'medium',lessonId:'medium-7',consonants:['บ'],vowels:['ใ-'],rules:['vowel-before'],explanation:'ใ + บ = bai.'},
  {id:'jai',romanAlternates:['jai'],meaning:'heart / mind',emoji:'❤️',level:'medium',lessonId:'medium-7',consonants:['จ'],vowels:['ใ-'],rules:['vowel-before'],explanation:'ใ + จ = jai.'},
  {id:'mao',romanAlternates:['mao'],meaning:'drunk',emoji:'🥴',level:'medium',lessonId:'medium-8',consonants:['ม'],vowels:['เ-า'],rules:['vowel-before'],explanation:'เ + ม + า = mao.'},
  {id:'bao',romanAlternates:['bao'],meaning:'light / gentle',emoji:'🪶',level:'medium',lessonId:'medium-8',consonants:['บ'],vowels:['เ-า'],rules:['vowel-before'],explanation:'เ + บ + า = bao.'},
  {id:'rao',romanAlternates:['rao'],meaning:'we / us',emoji:'👥',level:'medium',lessonId:'medium-8',consonants:['ร'],vowels:['เ-า'],rules:['vowel-before'],explanation:'เ + ร + า = rao.'},
  {id:'ao',romanAlternates:['ao'],meaning:'take / want',emoji:'🫴',level:'medium',lessonId:'medium-8',consonants:['อ'],vowels:['เ-า'],rules:['vowel-before','vowel-carrier'],explanation:'เ + อ + า = ao.'},
  {id:'maak',romanAlternates:['maak'],meaning:'very / much',emoji:'📈',level:'medium',lessonId:'medium-1',consonants:['ม','ก'],vowels:['า'],rules:['final-consonant'],explanation:'ม + า + final ก = maak. Final ก = k.'},
  {id:'gin',romanAlternates:['gin','kin'],meaning:'eat',emoji:'🍽️',level:'medium',lessonId:'medium-1',consonants:['ก','น'],vowels:['ิ'],rules:['final-consonant'],explanation:'ก + ิ + final น = gin.'},
  {id:'bpaak',romanAlternates:['bpaak','paak'],meaning:'mouth',emoji:'👄',level:'medium',lessonId:'medium-1',consonants:['ป','ก'],vowels:['า'],rules:['final-consonant'],explanation:'ป + า + final ก = bpaak.'},
  {id:'naan',romanAlternates:['naan'],meaning:'long (time)',emoji:'⏱️',level:'medium',lessonId:'medium-1',consonants:['น','น'],vowels:['า'],rules:['final-consonant'],explanation:'น + า + final น = naan.'},
  {id:'dtaak',romanAlternates:['dtaak','taak'],meaning:'dry in the sun',emoji:'☀️',level:'medium',lessonId:'medium-2',consonants:['ต','ก'],vowels:['า'],rules:['final-consonant'],explanation:'ต + า + final ก = dtaak.'},
  {id:'jaak',romanAlternates:['jaak'],meaning:'from',emoji:'📤',level:'medium',lessonId:'medium-2',consonants:['จ','ก'],vowels:['า'],rules:['final-consonant'],explanation:'จ + า + final ก = jaak.'},
  {id:'phaan',romanAlternates:['phaan'],meaning:'ceremonial tray',emoji:'🕯️',level:'medium',lessonId:'medium-2',consonants:['พ','น'],vowels:['า'],rules:['final-consonant'],explanation:'พ + า + final น = phaan.'},
  {id:'din',romanAlternates:['din'],meaning:'soil / earth',emoji:'🌍',level:'medium',lessonId:'medium-3',consonants:['ด','น'],vowels:['ิ'],rules:['final-consonant'],explanation:'ด + ิ + final น = din.'},
  {id:'chaan',romanAlternates:['chaan'],meaning:'veranda / platform',emoji:'🏠',level:'medium',lessonId:'medium-3',consonants:['ช','น'],vowels:['า'],rules:['final-consonant'],explanation:'ช + า + final น = chaan.'},
  {id:'nom',romanAlternates:['nom'],meaning:'milk',emoji:'🥛',level:'medium',lessonId:'medium-10',consonants:['น','ม'],vowels:[],rules:['final-consonant','implicit-o'],explanation:'Final ม = m. Implicit o.'},
  {id:'bon',romanAlternates:['bon'],meaning:'on / above',emoji:'⬆️',level:'medium',lessonId:'medium-10',consonants:['บ','น'],vowels:[],rules:['final-consonant','implicit-o'],explanation:'Final น = n. Implicit o.'},
  {id:'mong',thai:'มอง',romanAlternates:['mong'],meaning:'look / watch',emoji:'👁️',level:'medium',lessonId:'medium-10',consonants:['ม','อ','ง'],vowels:[],rules:['final-consonant','vowel-carrier'],explanation:'ม + อ + final ง = mong. Written อ = o (not hidden).',
    readingUnits:[
      {kind:'consonant',key:'consonant:ม',symbol:'ม',label:'ม = m',thai:'ม',roman:'m',role:'initial'},
      {kind:'vowel',key:'vowel:อ',symbols:['อ'],symbol:'อ',label:'อ = o',thai:'อ',roman:'o',hint:'อ written after the consonant is short o.'},
      {kind:'consonant',key:'consonant:ง:final',symbol:'ง',label:'ง = ng (final)',thai:'ง',roman:'ng',role:'final'},
    ]},
  {id:'khon',romanAlternates:['khon'],meaning:'person',emoji:'👤',level:'medium',lessonId:'medium-10',consonants:['ค','น'],vowels:[],rules:['final-consonant','implicit-o'],explanation:'Implicit o between ค and น.'},
  {id:'jon',romanAlternates:['jon'],meaning:'until / poor',emoji:'🔚',level:'medium',lessonId:'medium-10',consonants:['จ','น'],vowels:[],rules:['final-consonant','implicit-o'],explanation:'Implicit o vowel.'},
  {id:'khaa2',romanAlternates:['khaa'],meaning:'leg',emoji:'🦵',level:'advanced',lessonId:'advanced-1',consonants:['ข'],vowels:['า'],rules:['open-syllable'],explanation:'ข = kh (high class).'},
  {id:'sii',romanAlternates:['sii'],meaning:'colour',emoji:'🎨',level:'advanced',lessonId:'advanced-1',consonants:['ส'],vowels:['ี'],rules:['open-syllable'],explanation:'ส = s (high class).'},
  {id:'fan',romanAlternates:['fan'],meaning:'tooth',emoji:'🦷',level:'advanced',lessonId:'advanced-1c',consonants:['ฟ','น'],vowels:['ั'],rules:['final-consonant'],explanation:'ฟ + ั + final น = fan (tooth). ั is short a above the consonant — not a missing vowel and not ะ.'},
  {id:'fuu',romanAlternates:['fuu'],meaning:'fluffy / to rise (as dough)',emoji:'🍞',level:'advanced',lessonId:'advanced-1',consonants:['ฟ'],vowels:['ู'],rules:['open-syllable'],explanation:'ฟ + ู = fuu.'},
  {id:'saa',romanAlternates:['saa'],meaning:'sa (loan syllable in names/foods)',emoji:'🥟',level:'advanced',lessonId:'advanced-1',consonants:['ซ'],vowels:['า'],rules:['open-syllable'],explanation:'ซ = s. Clip from common foods (ซาลาเปา).'},
  {id:'thaa2',romanAlternates:['thaam'],meaning:'ask',emoji:'❓',level:'advanced',lessonId:'advanced-1b',consonants:['ถ','ม'],vowels:['า'],rules:['final-consonant'],explanation:'ถ + า + final ม = thaam.'},
  {id:'phaa2',romanAlternates:['phaa'],meaning:'cliff',emoji:'⛰️',level:'advanced',lessonId:'advanced-1b',consonants:['ผ'],vowels:['า'],rules:['open-syllable'],explanation:'ผ = ph (high class).'},
  {id:'faa2',romanAlternates:['faa'],meaning:'lid / wall',emoji:'🫙',level:'advanced',lessonId:'advanced-1b',consonants:['ฝ'],vowels:['า'],rules:['open-syllable'],explanation:'ฝ = f (high class).'},
  {id:'khaa_tone',thai:'ข้า',romanAlternates:['khaa'],meaning:'I (archaic/servant) / kill',emoji:'🗡️',level:'advanced',lessonId:'advanced-2',consonants:['ข'],vowels:['า','้'],rules:['tone-mark'],explanation:'ข้า with tone mark.'},
  {id:'suay',thai:'สวย',romanAlternates:['suay','suai'],meaning:'beautiful',emoji:'✨',level:'advanced',lessonId:'advanced-2',consonants:['ส','ว','ย'],vowels:['-วย'],rules:['w-vowel-ua'],explanation:'ส + วย = suay. ว is the ua vowel here (not “w”), and ย is the final — not implicit o.'},
  {id:'sii_zee',romanAlternates:['sii'],meaning:'C (letter) / series clip',emoji:'©️',level:'advanced',lessonId:'advanced-1',consonants:['ซ'],vowels:['ี'],rules:['open-syllable'],explanation:'ซี — long ii with ซ.'},
  {id:'thung',romanAlternates:['thung'],meaning:'bag',emoji:'🛍️',level:'advanced',lessonId:'advanced-1b',consonants:['ถ','ง'],vowels:['ุ'],rules:['final-consonant'],explanation:'ถุง = bag.'},
  {id:'phii',romanAlternates:['phii'],meaning:'ghost',emoji:'👻',level:'advanced',lessonId:'advanced-1b',consonants:['ผ'],vowels:['ี'],rules:['open-syllable'],explanation:'ผี = ghost.'},
  {id:'fon',romanAlternates:['fon'],meaning:'rain',emoji:'🌧️',level:'advanced',lessonId:'advanced-1b',consonants:['ฝ','น'],vowels:[],rules:['final-consonant','implicit-o'],explanation:'ฝน = rain.'},
  {id:'khao',romanAlternates:['khao'],meaning:'he/she / mountain',emoji:'🗻',level:'advanced',lessonId:'advanced-2',consonants:['ข','อ'],vowels:['เ-า'],rules:['vowel-before','vowel-carrier'],explanation:'ข + เ-า = khao.'},
  {id:'khaao',thai:'ข้าว',romanAlternates:['khaao'],meaning:'rice',emoji:'🍚',level:'advanced',lessonId:'advanced-2',consonants:['ข','ว'],vowels:['า','้'],rules:['tone-mark','final-consonant'],explanation:'ข้าว = rice.'},
  {id:'raan',thai:'ร้าน',romanAlternates:['raan'],meaning:'shop',emoji:'🏪',level:'advanced',lessonId:'advanced-2',consonants:['ร','น'],vowels:['า','้'],rules:['final-consonant','tone-mark'],explanation:'ร้าน = shop.'},
  {id:'baan',thai:'บ้าน',romanAlternates:['baan'],meaning:'house',emoji:'🏡',level:'advanced',lessonId:'advanced-2',consonants:['บ','น'],vowels:['า','้'],rules:['final-consonant','tone-mark'],explanation:'บ้าน = house.'},
  {id:'naam',thai:'น้ำ',romanAlternates:['naam','nam'],meaning:'water',emoji:'💧',level:'advanced',lessonId:'advanced-2',consonants:['น'],vowels:['ำ','้'],rules:['tone-mark','special-vowel'],explanation:'น้ำ = water. ำ = am (no separate ม).',
    readingUnits:[
      {kind:'consonant',key:'consonant:น',symbol:'น',label:'น = n',thai:'น',roman:'n',role:'initial'},
      {kind:'vowel',key:'vowel:ำ',symbols:['ำ'],label:'ำ = aam',thai:'◌ำ',roman:'aam'},
    ]},
  {id:'sawasdee',thai:'สวัสดี',romanAlternates:['sa-wat-dii','sawasdee','sawatdii','sawadee','sawatdee'],meaning:'hello',emoji:'🙏',level:'advanced',lessonId:'advanced-2',consonants:['ส','ว','ส','ด'],vowels:['ั','ี'],rules:['multi-syllable','final-consonant','final-sound-map'],explanation:'สวัสดี — decode syllable by syllable. สั uses ั (short a above).',
    readingUnits:[
      {kind:'consonant',key:'consonant:ส',symbol:'ส',label:'ส = s',thai:'ส',roman:'s',role:'initial'},
      {kind:'vowel',key:'vowel:a-open',symbols:[],label:'short a',thai:'◌ะ',roman:'a'},
      {kind:'consonant',key:'consonant:ว',symbol:'ว',label:'ว = w',thai:'ว',roman:'w',role:'initial'},
      {kind:'vowel',key:'vowel:ั',symbols:['ั'],label:'ั = a',thai:'◌ั',roman:'a'},
      {kind:'consonant',key:'consonant:ส:final',symbol:'ส',label:'ส → t (final)',thai:'ส',roman:'t',role:'final'},
      {kind:'consonant',key:'consonant:ด',symbol:'ด',label:'ด = d',thai:'ด',roman:'d',role:'initial'},
      {kind:'vowel',key:'vowel:ี',symbols:['ี'],label:'ี = ii',thai:'◌ี',roman:'ii'},
    ]},
  {id:'khopkhun',thai:'ขอบคุณ',romanAlternates:['khop-khun','khopkhun','kobkhun','khobkhun'],meaning:'thank you',emoji:'💝',level:'advanced',lessonId:'advanced-2',consonants:['ข','อ','บ','ค','น'],vowels:['ุ'],rules:['final-consonant','final-sound-map','multi-syllable','implicit-o','vowel-carrier'],explanation:'ขอบคุณ — first syllable ends บ→p; two closed syllables.',
    readingUnits:[
      {kind:'consonant',key:'consonant:ข',symbol:'ข',label:'ข = kh',thai:'ข',roman:'kh',role:'initial'},
      {kind:'vowel',key:'rule:implicit-o',rule:'implicit-o',label:'Hidden short o',thai:'◌◌',roman:'o'},
      {kind:'consonant',key:'consonant:บ:final',symbol:'บ',label:'บ → p (final)',thai:'บ',roman:'p',role:'final'},
      {kind:'consonant',key:'consonant:ค',symbol:'ค',label:'ค = kh',thai:'ค',roman:'kh',role:'initial'},
      {kind:'vowel',key:'vowel:ุ',symbols:['ุ'],label:'ุ = u',thai:'◌ุ',roman:'u'},
      {kind:'consonant',key:'consonant:น:final',symbol:'น',label:'น = n (final)',thai:'น',roman:'n',role:'final'},
    ]},
  {id:'ahaan',thai:'อาหาร',romanAlternates:['aa-haan','ahaan','aahaan','ahan','aharn'],meaning:'food',emoji:'🍲',level:'advanced',lessonId:'advanced-2',consonants:['อ','ห','ร'],vowels:['า'],rules:['vowel-carrier','final-consonant','final-sound-map','multi-syllable'],explanation:'อาหาร — อา + หาร. Final ร → n.',
    readingUnits:[
      {kind:'vowel',key:'vowel:า',symbols:['า'],label:'อา = aa',thai:'อา',roman:'aa'},
      {kind:'consonant',key:'consonant:ห',symbol:'ห',label:'ห = h',thai:'ห',roman:'h',role:'initial'},
      {kind:'vowel',key:'vowel:า:2',symbols:['า'],label:'า = aa',thai:'◌า',roman:'aa'},
      {kind:'consonant',key:'consonant:ร:final',symbol:'ร',label:'ร → n (final)',thai:'ร',roman:'n',role:'final',hint:'Final ร sounds like n, not “r”.'},
    ]},
  {id:'kho',romanAlternates:['kho'],meaning:'ask / request',emoji:'🙏',level:'advanced',lessonId:'advanced-2',consonants:['ข','อ'],vowels:[],rules:['vowel-carrier','implicit-o'],explanation:'ขอ = ask.'},
  {id:'som',romanAlternates:['som'],meaning:'orange (fruit)',emoji:'🍊',level:'advanced',lessonId:'advanced-2',consonants:['ส','ม'],vowels:['้'],rules:['final-consonant','tone-mark','implicit-o'],explanation:'ส้ม = orange.'},
  {id:'maa_dog',romanAlternates:['maa'],meaning:'dog',emoji:'🐶',level:'advanced',lessonId:'advanced-1c',consonants:['ห','ม'],vowels:['า'],rules:['open-syllable','leading-h'],explanation:'หมา = dog. Leading ห before ม is silent for class; read maa (not hmaa).'},
  {id:'ron',thai:'ร้อน',romanAlternates:['ron'],meaning:'hot',emoji:'🔥',level:'advanced',lessonId:'advanced-2',consonants:['ร','อ','น'],vowels:['้'],rules:['final-consonant','tone-mark','vowel-carrier'],explanation:'ร้อน = hot. Written อ = o (not โ-).',
    readingUnits:[
      {kind:'consonant',key:'consonant:ร',symbol:'ร',label:'ร = r',thai:'ร',roman:'r',role:'initial'},
      {kind:'vowel',key:'vowel:อ',symbols:['อ'],symbol:'อ',label:'อ = o',thai:'อ',roman:'o',hint:'อ written after the consonant is short o.'},
      {kind:'consonant',key:'consonant:น:final',symbol:'น',label:'น = n (final)',thai:'น',roman:'n',role:'final'},
    ]},
  {id:'klaang',thai:'กลาง',romanAlternates:['klaang','klang'],meaning:'middle',emoji:'↔️',level:'advanced',lessonId:'advanced-2',consonants:['ก','ล','ง'],vowels:['า'],rules:['final-consonant'],explanation:'กลาง = middle.'},
  {id:'jing',thai:'จริง',romanAlternates:['jing','jring'],meaning:'true / really',emoji:'✅',level:'advanced',lessonId:'advanced-2',consonants:['จ','ร','ง'],vowels:['ิ'],rules:['final-consonant'],explanation:'จริง = true. Spoken jing; jring is orthographic.',
    readingUnits:[
      {kind:'consonant',key:'consonant:จ',symbol:'จ',label:'จ = j',thai:'จ',roman:'j',role:'initial'},
      {kind:'vowel',key:'vowel:ิ',symbols:['ิ'],label:'ิ = i',thai:'◌ิ',roman:'i'},
      {kind:'consonant',key:'consonant:ง:final',symbol:'ง',label:'ง = ng (final)',thai:'ง',roman:'ng',role:'final'},
    ]},
  {id:'card_mid',romanAlternates:['mid'],meaning:'mid-class consonant (ก)',emoji:'🔤',level:'advanced',lessonId:'advanced-4',consonants:['ก'],vowels:[],rules:['consonant-class'],explanation:'ก is mid class.'},
  {id:'card_high',romanAlternates:['high'],meaning:'high-class consonant (ส)',emoji:'🔤',level:'advanced',lessonId:'advanced-4',consonants:['ส'],vowels:[],rules:['consonant-class'],explanation:'ส is high class.'},
  {id:'card_low',romanAlternates:['low'],meaning:'low-class consonant (ค)',emoji:'🔤',level:'advanced',lessonId:'advanced-4',consonants:['ค'],vowels:[],rules:['consonant-class'],explanation:'ค is low class.'},
  {id:'tone_ek',thai:'ม่า',romanAlternates:['maa'],meaning:'low-tone example (mai ek)',emoji:'📉',level:'advanced',lessonId:'advanced-3',consonants:['ม'],vowels:['า','่'],rules:['tone-mark'],explanation:'่ = mai ek.'},
  {id:'tone_tho',thai:'ม้า',romanAlternates:['maa'],meaning:'horse (falling tone)',emoji:'🐴',level:'advanced',lessonId:'advanced-3',consonants:['ม'],vowels:['า','้'],rules:['tone-mark'],explanation:'ม้า = horse. ้ = mai tho.'},
  {id:'silent_ex',thai:'เธอร์ม',romanAlternates:['term','therm'],meaning:'therm- (loan root; silent ์)',emoji:'🌡️',level:'advanced',lessonId:'advanced-6',consonants:['ท','ร','ม'],vowels:['เ-','์'],rules:['vowel-before','silent-mark'],explanation:'เธอร์ม — loan therm-; ์ silences ร in Thai spelling; learner reading keeps r.',
    readingUnits:[
      {kind:'consonant',key:'consonant:ท',symbol:'ท',label:'ท = t',thai:'ท',roman:'t',role:'initial'},
      {kind:'vowel',key:'vowel:เ-',symbols:['เ-'],label:'เ- = e',thai:'เ◌',roman:'e'},
      {kind:'consonant',key:'consonant:ร',symbol:'ร',label:'ร = r',thai:'ร',roman:'r',role:'initial'},
      {kind:'consonant',key:'consonant:ม:final',symbol:'ม',label:'ม = m (final)',thai:'ม',roman:'m',role:'final'},
    ]},
  {id:'fim',thai:'ฟิล์ม',romanAlternates:['fim','film'],meaning:'film',emoji:'🎞️',level:'advanced',lessonId:'advanced-6',consonants:['ฟ','ม'],vowels:['ิ','์'],rules:['silent-mark','final-consonant'],explanation:'ฟิล์ม — silent ์.'},
  {id:'gaafae',thai:'กาแฟ',romanAlternates:['gaafae','kaafae','gafae','kaafe'],meaning:'coffee',emoji:'☕',level:'advanced',lessonId:'advanced-7',consonants:['ก','ฟ'],vowels:['า','แ-'],rules:['vowel-before','multi-syllable'],explanation:'กา + แฟ = coffee.',
    readingUnits:[
      {kind:'consonant',key:'consonant:ก',symbol:'ก',label:'ก = k/g',thai:'ก',roman:'k',role:'initial'},
      {kind:'vowel',key:'vowel:า',symbols:['า'],label:'า = aa',thai:'◌า',roman:'aa'},
      {kind:'consonant',key:'consonant:ฟ',symbol:'ฟ',label:'ฟ = f',thai:'ฟ',roman:'f',role:'initial'},
      {kind:'vowel',key:'vowel:แ-',symbols:['แ-'],label:'แ- = ae',thai:'แ◌',roman:'ae'},
    ]},
  {id:'thanon',thai:'ถนน',romanAlternates:['tha-non','thanon'],meaning:'road',emoji:'🛣️',level:'advanced',lessonId:'advanced-7',consonants:['ถ','น','น'],vowels:[],rules:['final-consonant','implicit-o','multi-syllable'],explanation:'ถนน = road.',
    readingUnits:[
      {kind:'consonant',key:'consonant:ถ',symbol:'ถ',label:'ถ = th',thai:'ถ',roman:'th',role:'initial'},
      {kind:'vowel',key:'vowel:a-open',symbols:[],label:'short a',thai:'◌ะ',roman:'a'},
      {kind:'consonant',key:'consonant:น',symbol:'น',label:'น = n',thai:'น',roman:'n',role:'initial'},
      {kind:'vowel',key:'rule:implicit-o',rule:'implicit-o',label:'Hidden short o',thai:'◌◌',roman:'o'},
      {kind:'consonant',key:'consonant:น:final',symbol:'น',label:'น = n (final)',thai:'น',roman:'n',role:'final'},
    ]},
  {id:'roongraem',thai:'โรงแรม',romanAlternates:['roong-raem','roongraem'],meaning:'hotel',emoji:'🏨',level:'advanced',lessonId:'advanced-7',consonants:['ร','ง','ร','ม'],vowels:['โ-','แ-'],rules:['vowel-before','final-consonant','multi-syllable'],explanation:'โรง + แรม = hotel.',
    readingUnits:[
      {kind:'consonant',key:'consonant:ร',symbol:'ร',label:'ร = r',thai:'ร',roman:'r',role:'initial'},
      {kind:'vowel',key:'vowel:โ-',symbols:['โ-'],label:'โ- = oo',thai:'โ◌',roman:'oo'},
      {kind:'consonant',key:'consonant:ง:final',symbol:'ง',label:'ง = ng (final)',thai:'ง',roman:'ng',role:'final'},
      {kind:'consonant',key:'consonant:ร:2',symbol:'ร',label:'ร = r',thai:'ร',roman:'r',role:'initial'},
      {kind:'vowel',key:'vowel:แ-',symbols:['แ-'],label:'แ- = ae',thai:'แ◌',roman:'ae'},
      {kind:'consonant',key:'consonant:ม:final',symbol:'ม',label:'ม = m (final)',thai:'ม',roman:'m',role:'final'},
    ]},
  {id:'bpeert',thai:'เปิด',romanAlternates:['bpoet','poet','bpert','pert'],meaning:'open',emoji:'🔓',level:'advanced',lessonId:'medium-9',consonants:['ป','ด'],vowels:['เ-','ิ'],rules:['vowel-before','final-consonant','final-sound-map'],explanation:'เปิด — เ◌ิ = oe; final ด→t (not “d”).'},
  {id:'bpit',romanAlternates:['bpit','pit'],meaning:'closed',emoji:'🔒',level:'advanced',lessonId:'medium-9',consonants:['ป','ด'],vowels:['ิ'],rules:['final-consonant','final-sound-map'],explanation:'ปิด — final ด→t (not “d”).'},
  {id:'khao2',thai:'เข้า',romanAlternates:['khao'],meaning:'enter',emoji:'🚪',level:'advanced',lessonId:'advanced-7',consonants:['ข'],vowels:['เ-า','้'],rules:['vowel-before','tone-mark'],explanation:'เข้า = enter (เ-า = ao).'},
  {id:'awk',thai:'ออก',romanAlternates:['awk','ok'],meaning:'exit',emoji:'🚪',level:'advanced',lessonId:'advanced-7',consonants:['อ','ก'],vowels:[],rules:['vowel-carrier','final-consonant','implicit-o'],explanation:'ออก = exit.'},
  {id:'thiang',thai:'เที่ยง',romanAlternates:['thiang'],meaning:'noon',emoji:'🕛',level:'advanced',lessonId:'advanced-7',consonants:['ท','ย','ง'],vowels:['เ-','ี'],rules:['vowel-before','final-consonant'],explanation:'เที่ยง = noon (เ◌ีย = ia).',
    readingUnits:[
      {kind:'consonant',key:'consonant:ท',symbol:'ท',label:'ท = th',thai:'ท',roman:'th',role:'initial'},
      {kind:'vowel',key:'vowel:เ-ีย',symbols:['เ-','ี','ย'],label:'เ◌ีย = ia',thai:'เ◌ีย',roman:'ia'},
      {kind:'consonant',key:'consonant:ง:final',symbol:'ง',label:'ง = ng (final)',thai:'ง',roman:'ng',role:'final'},
    ]},
  {id:'nakrian',thai:'นักเรียน',romanAlternates:['nak-rian','nakrian'],meaning:'student',emoji:'🎓',level:'advanced',lessonId:'advanced-7',consonants:['น','ก','ร','ย','น'],vowels:['ั','ิ','เ-','ี'],rules:['final-consonant','multi-syllable','vowel-before'],explanation:'นักเรียน = student. นั uses ั (short a above).',
    readingUnits:[
      {kind:'consonant',key:'consonant:น',symbol:'น',label:'น = n',thai:'น',roman:'n',role:'initial'},
      {kind:'vowel',key:'vowel:ั',symbols:['ั'],label:'ั = a',thai:'◌ั',roman:'a'},
      {kind:'consonant',key:'consonant:ก:final',symbol:'ก',label:'ก = k (final)',thai:'ก',roman:'k',role:'final'},
      {kind:'consonant',key:'consonant:ร',symbol:'ร',label:'ร = r',thai:'ร',roman:'r',role:'initial'},
      {kind:'vowel',key:'vowel:เ-ีย',symbols:['เ-','ี','ย'],label:'เ◌ีย = ia',thai:'เ◌ีย',roman:'ia'},
      {kind:'consonant',key:'consonant:น:final',symbol:'น',label:'น = n (final)',thai:'น',roman:'n',role:'final'},
    ]},
  {id:'roongrian',thai:'โรงเรียน',romanAlternates:['roong-rian','roongrian'],meaning:'school',emoji:'🏫',level:'advanced',lessonId:'advanced-7',consonants:['ร','ง','ร','ย','น'],vowels:['โ-','เ-','ี'],rules:['vowel-before','final-consonant','multi-syllable'],explanation:'โรงเรียน = school.',
    readingUnits:[
      {kind:'consonant',key:'consonant:ร',symbol:'ร',label:'ร = r',thai:'ร',roman:'r',role:'initial'},
      {kind:'vowel',key:'vowel:โ-',symbols:['โ-'],label:'โ- = oo',thai:'โ◌',roman:'oo'},
      {kind:'consonant',key:'consonant:ง:final',symbol:'ง',label:'ง = ng (final)',thai:'ง',roman:'ng',role:'final'},
      {kind:'consonant',key:'consonant:ร:2',symbol:'ร',label:'ร = r',thai:'ร',roman:'r',role:'initial'},
      {kind:'vowel',key:'vowel:เ-ีย',symbols:['เ-','ี','ย'],label:'เ◌ีย = ia',thai:'เ◌ีย',roman:'ia'},
      {kind:'consonant',key:'consonant:น:final',symbol:'น',label:'น = n (final)',thai:'น',roman:'n',role:'final'},
    ]},
  {id:'maew',romanAlternates:['maew'],meaning:'cat',emoji:'🐱',level:'advanced',lessonId:'advanced-7',consonants:['ม','ว'],vowels:['แ-'],rules:['vowel-before','final-consonant'],explanation:'แมว = cat.'},
  {id:'bplaa',thai:'ปลา',romanAlternates:['bplaa','plaa'],meaning:'fish',emoji:'🐟',level:'advanced',lessonId:'advanced-7',consonants:['ป','ล'],vowels:['า'],rules:['open-syllable'],explanation:'ปลา = fish.'},
];
const LESSONS = [
  {id:'basic-1',level:'basic',order:1,title:'The Thai syllable core',unlockAfter:null,isBoss:false,
    introduces:{consonants:['ก','ม'],vowels:['า'],rules:['consonant-core','long-aa','open-syllable']},
    teachingCards:[{title:'Thai syllables have a core',body:'Thai syllables are built around a main consonant. Vowels attach around that consonant. Today the vowel is easy: า comes after the consonant and sounds like long aa.'},{title:'Font awareness from day one',body:'The same Thai symbol may look different across fonts. You will learn each symbol in looped and modern fonts from the very beginning.'}],
    examples:['gaa','maa'],practiceWordIds:['gaa','maa']},
  {id:'basic-2',level:'basic',order:2,title:'Add น',unlockAfter:'basic-1',isBoss:false,
    introduces:{consonants:['น'],vowels:[],rules:[]},
    teachingCards:[{title:'Same pattern, new consonant',body:'น = n. Compare น with ม — they look similar in some fonts. Practice telling them apart across all font styles.'}],
    examples:['naa','maa'],practiceWordIds:['naa','maa','gaa']},
  {id:'basic-3',level:'basic',order:3,title:'Short a',unlockAfter:'basic-2',isBoss:false,
    introduces:{consonants:[],vowels:['ะ'],rules:['short-a']},
    teachingCards:[{title:'Vowel length matters',body:'า = long aa. ะ = short a. The small mark makes a big difference. Small marks also vary slightly by font and size.'}],
    examples:['ma','ka','na'],practiceWordIds:['ma','ka','na','maa']},
  {id:'basic-4',level:'basic',order:4,title:'i and ii',unlockAfter:'basic-3',isBoss:false,
    introduces:{consonants:[],vowels:['ิ','ี'],rules:['vowel-above']},
    teachingCards:[{title:'Vowels above consonants',body:'Vowels can be marks above (or below) consonants. Find the consonant first, then the vowel. Small vowel marks must be recognised even in different fonts.'}],
    examples:['mi','mii'],practiceWordIds:['mi','mii','maa','gaa']},
  {id:'basic-5',level:'basic',order:5,title:'Vowel before consonant: เ-',unlockAfter:'basic-4',isBoss:false,
    introduces:{consonants:[],vowels:['เ-'],rules:['vowel-before','compound-short-e']},
    teachingCards:[
      {title:'Visual order ≠ pronunciation order',body:'เ is written before the consonant but pronounced after it. เก is ke/ge, not ek.'},
      {title:'เ-ะ is one short e — not “ea”',body:'You already know ะ alone = short a (กะ = ka). When เ and ะ wrap the same consonant, they fuse into one short e. เกะ = ke/ge. Never add an extra “a”: it is not “kea” or “lea”.'},
    ],
    examples:['ke'],practiceWordIds:['ke','maa','mii','gaa']},
  {id:'basic-6',level:'basic',order:6,title:'Add ป and บ',unlockAfter:'basic-5',isBoss:false,
    introduces:{consonants:['ป','บ'],vowels:[],rules:[]},
    teachingCards:[{title:'Similar-looking consonants',body:'ป = bp/p (unaspirated) and บ = b. These are visually similar — บ vs ป is an important font-sensitive distinction.'}],
    examples:['paa','baa','bpe'],practiceWordIds:['paa','baa','bpe','be']},
  {id:'basic-7',level:'basic',order:7,title:'Vowel before consonant: โ-',unlockAfter:'basic-6',isBoss:false,
    introduces:{consonants:[],vowels:['โ-'],rules:['compound-short-o']},
    teachingCards:[
      {title:'โ works like เ',body:'โ is written before the consonant but pronounced after it, just like เ. โม = mo.'},
      {title:'โ-ะ is one short o — not “oa”',body:'Same fusion as เ-ะ: โ + ะ around a consonant = one short o. โกะ = ko/go — not “koa”.'},
    ],
    examples:['ko','mo','bo'],practiceWordIds:['ko','mo','bo','bpo']},
  {id:'basic-8',level:'basic',order:8,title:'Add ต',unlockAfter:'basic-7',isBoss:false,
    introduces:{consonants:['ต'],vowels:[],rules:[]},
    teachingCards:[{title:'Now โต is allowed',body:'ต = dt/t. Now that ต is introduced, you can read โต (big). Distinguish ต from already known letters in modern fonts.'}],
    examples:['taa','dto','dte'],practiceWordIds:['taa','dto','dte','dtii']},
  {id:'basic-9',level:'basic',order:9,title:'Add ล and ร',unlockAfter:'basic-8',isBoss:false,
    introduces:{consonants:['ล','ร'],vowels:[],rules:[]},
    teachingCards:[{title:'ล vs ร',body:'ล = l, ร = r (though casual speech may sound like l). Lead with open long vowels (ลา, รา). Short forms เละ / โละ only show up after the เ-ะ / โ-ะ fusion rules from earlier lessons — not “lea” / “loa”.'}],
    examples:['laa','raa'],practiceWordIds:['laa','raa','lo','le']},
  {id:'basic-10',level:'basic',order:10,title:'Add ง',unlockAfter:'basic-9',isBoss:false,
    introduces:{consonants:['ง'],vowels:[],rules:[]},
    teachingCards:[{title:'Syllables starting with ng',body:'Thai can start syllables with ng. Learn ง shape across all fonts now, because stylised ง can become confusing later.'}],
    examples:['ngaa'],practiceWordIds:['ngaa','maa','naa','dto']},
  {id:'basic-boss',level:'basic',order:11,title:'Basic Boss Test',unlockAfter:'basic-10',isBoss:true,bossQuestions:25,bossFonts:['looped','modern','mixed'],
    introduces:{consonants:[],vowels:[],rules:[]},
    teachingCards:[{title:'Basic Boss Test',body:'This test covers all Basic consonants and vowels. You need 85% to pass. Includes looped, modern, and mixed fonts.'}],
    examples:[],practiceWordIds:['gaa','maa','naa','mii','dto','ngaa','paa','baa','laa','raa']},
  {id:'medium-1',level:'medium',order:12,title:'Add ค พ ห + closed syllables',unlockAfter:'basic-boss',isBoss:false,
    introduces:{consonants:['ค','พ','ห'],vowels:[],rules:['aspirated','final-consonant']},
    teachingCards:[
      {title:'Aspirated consonants',body:'ค = kh and พ = ph are aspirated — not the same as ก and ป. The extra air makes a different sound.'},
      {title:'Syllables can end with a consonant',body:'Until now you mostly read open syllables (consonant + vowel). Thai also has closed syllables: consonant + vowel + final consonant. มาก = maak (ม + า + ก). From medium onward, expect 2-consonant words in practice and tests.'},
    ],
    examples:['khaa','phaa','maak','gin'],practiceWordIds:['khaa','phaa','haa','maak','gin','bpaak','naan']},
  {id:'medium-2',level:'medium',order:13,title:'Add ว ย จ',unlockAfter:'medium-1',isBoss:false,
    introduces:{consonants:['ว','ย','จ'],vowels:[],rules:[]},
    teachingCards:[{title:'Three more consonants',body:'ว = w, ย = y, จ = j. Compare ง vs จ when both are known. Keep practising closed syllables too — จาก, ตาก.'}],
    examples:['waa','jaan','jaak','dtaak'],practiceWordIds:['waa','yaa','jaan','jaak','dtaak','phaan']},
  {id:'medium-3',level:'medium',order:14,title:'Add ด ท ช and ู',unlockAfter:'medium-2',isBoss:false,
    introduces:{consonants:['ด','ท','ช'],vowels:['ู'],rules:[]},
    confusingPairIds:['mo-tho'],
    teachingCards:[
      {title:'New consonants and long uu',body:'ด = d, ท = th, ช = ch. ู = long uu (written below the consonant). Now you can read ดู (look/watch). Closed practice here uses finals that keep their sound: ดิน (din), ชาน (chaan).'},
      {title:'Critical: ม vs ท',body:'ท is new — and it looks a lot like ม (m) you already know. Pause on the contrast slide and memorise the notch on ท. Tests will check this pair often.'},
    ],
    examples:['thaa','tho','duu','din'],practiceWordIds:['thaa','tho','maa','mo','duu','chaan','din','nguu']},
  {id:'medium-4',level:'medium',order:15,title:'Add อ as vowel carrier',unlockAfter:'medium-3',isBoss:false,
    introduces:{consonants:['อ'],vowels:['เ-อ'],rules:['vowel-carrier','compound-oe']},
    teachingCards:[
      {title:'อ as vowel carrier',body:'อ can support a vowel when there is no other consonant. อา = aa, อี = ii, เอ = e, โอ = o.'},
      {title:'เ + consonant + อ = oe/er',body:'When เ and อ wrap a consonant, they make one oe/er sound. เจอ = joe (meet), เรอ = roe. Here อ is part of the vowel — not a silent leftover letter.'},
    ],
    examples:['aa_carrier','ii_carrier','e_carrier','o_carrier','je'],practiceWordIds:['aa_carrier','ii_carrier','e_carrier','o_carrier','je','re']},
  {id:'medium-5',level:'medium',order:16,title:'Add แ-',unlockAfter:'medium-4',isBoss:false,
    introduces:{consonants:[],vowels:['แ-'],rules:[]},
    teachingCards:[{title:'The แ- vowel',body:'แ- = ae sound, written before the consonant like เ- and โ-.'}],
    examples:['gae','phae','lae'],practiceWordIds:['gae','phae','bae','lae','nae']},
  {id:'medium-6',level:'medium',order:17,title:'Add ุ',unlockAfter:'medium-5',isBoss:false,
    introduces:{consonants:[],vowels:['ุ'],rules:['vowel-below']},
    teachingCards:[{title:'Short u below',body:'ุ = short u, written below the consonant. Pair with ู = long uu.'}],
    examples:['puu','lung','mum'],practiceWordIds:['puu','lung','mum','nguu']},
  {id:'medium-7',level:'medium',order:18,title:'Add ไ- and ใ-',unlockAfter:'medium-6',isBoss:false,
    introduces:{consonants:[],vowels:['ไ-','ใ-'],rules:[]},
    confusingPairIds:['o-mai-muan'],
    teachingCards:[
      {title:'Two ways to write ai',body:'ไ and ใ both sound like ai. ใ is used only in a limited set of words (~20). ไ vs ใ must be recognised visually.'},
      {title:'Critical: อ vs ใ',body:'ใ looks a lot like อ (the round o-shaped carrier). Pause on the contrast slide — the crest on top means ใ (ai), not อ. Tests will check this pair.'},
    ],
    examples:['bpai','gai','bai','jai'],practiceWordIds:['bpai','gai','bai','jai']},
  {id:'medium-8',level:'medium',order:19,title:'Add เ-า',unlockAfter:'medium-7',isBoss:false,
    introduces:{consonants:[],vowels:['เ-า'],rules:[]},
    teachingCards:[{title:'The ao vowel',body:'เ + า together make the ao sound. เมา = mao (drunk), เรา = rao (we).'}],
    examples:['mao','bao','rao','ao'],practiceWordIds:['mao','bao','rao','ao']},
  {id:'medium-9',level:'medium',order:20,title:'Final consonants deep dive',unlockAfter:'medium-8',isBoss:false,
    introduces:{consonants:[],vowels:[],rules:['final-sound-map']},
    teachingCards:[
      {title:'Final sounds — map them',body:'Until now closed practice mostly used น ม ง (sound stays n/m/ng) and ก as k. Some finals change sound: ด/ต → t, บ/ป → p, and ร/ล → n. The letter you see is not always the sound you hear.'},
      {title:'Critical: final ร and ล sound like n',body:'ร is “r” at the start of a syllable (รา = raa), but as a final it sounds like n — เวร = ween, not “weer”. Same for ล: นิล = nin, not “nil” as an English L ending. Memorise: final ร/ล → n.'},
    ],
    examples:['we','ni','khii','maak','gin'],practiceWordIds:['we','ni','khii','maak','gin']},
  {id:'medium-10',level:'medium',order:21,title:'Implicit short o',unlockAfter:'medium-9',isBoss:false,
    introduces:{consonants:[],vowels:[],rules:['implicit-o']},
    teachingCards:[{title:'Hidden vowel o',body:'If two consonants appear without a written vowel, Thai often inserts a short o. นม = nom (milk), คน = khon (person).'}],
    examples:['nom','bon','khon','jon'],practiceWordIds:['nom','bon','khon','jon']},
  {id:'medium-boss',level:'medium',order:22,title:'Medium Boss Test',unlockAfter:'medium-10',isBoss:true,bossQuestions:35,bossFonts:['looped','modern','mixed'],
    introduces:{consonants:[],vowels:[],rules:[]},
    teachingCards:[{title:'Medium Boss Test',body:'Covers all Basic and Medium material. All font modes. Need 85% to pass.'}],
    examples:[],practiceWordIds:['duu','chaa','bpai','jai','maak','nom','khon','phaa','yaa']},
  {id:'advanced-1',level:'advanced',order:23,title:'New consonants: ข ส ฟ ซ',unlockAfter:'medium-boss',isBoss:false,
    introduces:{consonants:['ข','ส','ฟ','ซ'],vowels:[],rules:[]},
    teachingCards:[
      {title:'Reminder: final ร/ล sound like n',body:'Before new letters: ร is “r” at the start (รา = raa), but as a final it is n — เวร = ween, not “weer”. Same for ล (นิล = nin).'},
      {title:'Four new consonants',body:'ข = kh (high class), ส = s, ฟ = f, ซ = s. Practice with vowels you already know (า ี ู). Confusing pairs come later — focus on these four shapes first.'},
    ],
    examples:['we','khaa2','sii','fuu','saa'],practiceWordIds:['we','ni','khaa2','sii','fuu','saa','sii_zee']},
  {id:'advanced-1b',level:'advanced',order:24,title:'New consonants: ถ ผ ฝ',unlockAfter:'advanced-1',isBoss:false,
    introduces:{consonants:['ถ','ผ','ฝ'],vowels:[],rules:[]},
    teachingCards:[
      {title:'Three more consonants',body:'ถ = th, ผ = ph, ฝ = f. Compare with letters you know: ถ vs ท, ผ vs พ, ฝ vs ฟ. Still only use vowels and finals already taught — no new marks yet.'},
    ],
    examples:['thaa2','phaa2','faa2'],practiceWordIds:['thaa2','phaa2','faa2','thung','phii','fon']},
  {id:'advanced-1c',level:'advanced',order:25,title:'Leading ห and ั',unlockAfter:'advanced-1b',isBoss:false,
    introduces:{consonants:[],vowels:['ั'],rules:['leading-h']},
    teachingCards:[
      {title:'Leading ห before ม น ง',body:'Sometimes ห sits in front of ม/น/ง. You still hear m/n/ng — not “hm/hn/hng”. หมู = muu (pig), หนู = nuu (mouse), หมา = maa (dog).'},
      {title:'New mark: ั (mai han-akat)',body:'ั is a short a written above the consonant. It usually needs a final consonant: ฟัน = fan (tooth). Do not treat it as a missing vowel, and do not confuse it with ะ (short a written after the consonant).'},
    ],
    examples:['muu','nuu','maa_dog','fan'],practiceWordIds:['muu','nuu','maa_dog','ngi','fan']},
  {id:'advanced-2',level:'advanced',order:26,title:'Common real-world words',unlockAfter:'advanced-1c',isBoss:false,
    introduces:{consonants:[],vowels:['ำ','้','-วย'],rules:['tone-mark','special-vowel','multi-syllable','w-vowel-ua']},
    teachingCards:[
      {title:'Real words with tone marks',body:'Tone mark ้ affects tone. ำ is a special vowel form. Full tone rules come later — for now, identify the mark and continue decoding.'},
      {title:'Critical: ว can be a vowel (uay)',body:'In สวย, ว is not consonant “w”. The pattern -วย makes the uay sound: ส + วย = suay (beautiful). Do not read it as s + o + w + y or as implicit o.'},
      {title:'Longer words = syllable chains',body:'From advanced onward you will read words with 3+ consonants. Decode one syllable at a time: สวัสดี, ขอบคุณ, อาหาร. Do not try to swallow the whole word at once.'},
    ],
    examples:['khao','khaao','raan','suay','sawasdee','khopkhun'],practiceWordIds:['khao','khaao','raan','baan','naam','suay','sawasdee','khopkhun','ahaan','klaang','jing']},
  {id:'advanced-3',level:'advanced',order:27,title:'Tone marks overview',unlockAfter:'advanced-2',isBoss:false,
    introduces:{consonants:[],vowels:['่','๊','๋'],rules:['tone-mark']},
    teachingCards:[{title:'Four tone marks',body:'่ mai ek, ้ mai tho, ๊ mai tri, ๋ mai chattawa. Tone marks affect tone but do not replace vowels. Exact tone depends on consonant class — learned next.'}],
    examples:['tone_ek','tone_tho'],practiceWordIds:['tone_ek','tone_tho']},
  {id:'advanced-4',level:'advanced',order:28,title:'Consonant classes simplified',unlockAfter:'advanced-3',isBoss:false,
    introduces:{consonants:[],vowels:[],rules:['consonant-class']},
    teachingCards:[{title:'Three consonant classes',body:'Mid: ก จ ด ต บ ป อ. High: ข ถ ผ ฝ ส ห. Low: ค ง ช ซ ท น พ ฟ ม ย ร ล ว. Class affects tone rules.'}],
    examples:['card_mid','card_high','card_low'],practiceWordIds:['card_mid','card_high','card_low']},
  {id:'advanced-5',level:'advanced',order:29,title:'Live and dead syllables',unlockAfter:'advanced-4',isBoss:false,
    introduces:{consonants:[],vowels:[],rules:['live-syllable','dead-syllable']},
    teachingCards:[{title:'Live vs dead',body:'Live syllables end in long vowel or sonorant (n, m, ng, w, y). Dead syllables end in short vowel or k/t/p.'}],
    examples:['maak','nom','gin','bpit'],practiceWordIds:['maak','nom','gin','bpit']},
  {id:'advanced-6',level:'advanced',order:30,title:'Silent mark',unlockAfter:'advanced-5',isBoss:false,
    introduces:{consonants:[],vowels:['์'],rules:['silent-mark']},
    teachingCards:[{title:'The silent mark ์',body:'์ (garan) makes a letter silent, often in loanwords or formal spellings.'}],
    examples:['silent_ex'],practiceWordIds:['silent_ex']},
  {id:'advanced-7',level:'advanced',order:31,title:'Multi-syllable words',unlockAfter:'advanced-6',isBoss:false,
    introduces:{consonants:[],vowels:[],rules:['multi-syllable','compound-oe-i']},
    teachingCards:[
      {title:'Long words = syllable chains',body:'Longer Thai words are built from syllables. Decode one syllable at a time. Do not panic at long words.'},
      {title:'Consonant clusters',body:'Two consonants before a vowel can blend: พ + ล = phl (as in เพลิน = phloen). Read them as one block, not p + l separately.'},
      {title:'เ◌ิ = oe — not i',body:'In some words เ with ิ above the next consonant makes oe, not e + i. เพลิน = phloen — not “phelin”. Do not treat ิ as a separate i vowel here.'},
    ],
    examples:['gaafae','thanon','phe'],practiceWordIds:['gaafae','thanon','roongraem','bpeert','khao2','phe','bplaa']},
  {id:'advanced-boss',level:'advanced',order:32,title:'Advanced Boss Test',unlockAfter:'advanced-7',isBoss:true,bossQuestions:50,bossFonts:['looped','modern','mixed'],
    introduces:{consonants:[],vowels:[],rules:[]},
    teachingCards:[{title:'Advanced Boss Test',body:'Final challenge! All material, all font modes. Need 85% to pass.'}],
    examples:[],practiceWordIds:['khao','khaao','baan','naam','gaafae','thanon','bpeert','bpit','sii','khaa2']},
];
